#!/usr/bin/env python3
"""Export candidate window bounds for Proposition 24, without exporting proofs.

Run from any directory. The reference program `verification/knuth_ranges.py`
computes the window bounds lo(W) and hi(W) of Section 6.6 exactly in Q(sqrt 5).
Every value has denominator dividing 8, so this exporter writes 8 lo(W) and
8 hi(W) as elements a + b sqrt 5 of Z[sqrt 5], together with the index of a
state whose output history is W. Lean checks every inequality of Proposition 24
from these candidates; neither this exporter nor the reference program is part
of the trusted proof base. The output is deterministic and records its source
digest.
"""
from __future__ import annotations

import hashlib
import json
from pathlib import Path
import sys

from lean_export import balanced_tree, indexed_checks, write_lean
from export_finite_certificate import REFERENCE, record

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REFERENCE))
from calculation import HistoryGraph, encode  # noqa: E402
from knuth_ranges import Q5, INV_PHI, START, window_bounds  # noqa: E402
from verify_tuples import explore  # noqa: E402


def scaled(value: Q5) -> str:
    """Render 8 * value, an element of Z[sqrt 5], as a Lean `ℤ√5` literal."""
    a, b = 8 * value.a, 8 * value.b
    if a.denominator != 1 or b.denominator != 1:
        raise SystemExit(f"window bound {value} does not lie in Z[sqrt 5] / 8")
    return f"⟨{a.numerator}, {b.numerator}⟩"


def main():
    source = REFERENCE / "history.json"
    graph = HistoryGraph.load(source)
    _initial, successors, _stats = explore(graph, START)
    states = list(successors)
    Y = {s: Q5(s.w - len(s.D) + 1) - s.z * INV_PHI for s in states}
    lo, hi = window_bounds(states, Y, {s: float(Y[s]) for s in states})
    index = {state: i for i, state in enumerate(sorted(record(s) for s in states))}
    witness = {}
    for s in states:
        witness[s.H_out] = min(witness.get(s.H_out, len(index)), index[record(s)])
    vertices = sorted(json.loads(source.read_text())["vertices"])
    by_code = {encode(word): word for word in lo}
    if sorted(by_code) != [vertex for vertex, _ in vertices]:
        raise SystemExit("the window bounds and the history graph have different vertices")
    entries = [f"({code}, ⟨{scaled(lo[word])}, {scaled(hi[word])}, {witness[word]}⟩)"
               for code, word in sorted(by_code.items())]

    lines = ["import Queens.Finite.WindowBound", "", "/-!",
             "# Generated window-bound data",
             "",
             "Candidate window bounds for Proposition 24 (Section 6.6), one entry for",
             "each vertex `W` of the history graph: `8 lo(W)` and `8 hi(W)` in `ℤ√5`,",
             "and the index of a state whose output history is `W`.",
             "Generated by `python3 scripts/export_window_bounds.py`; do not edit by hand.",
             "Lean checks every claimed property of these values.",
             f"Source history.json SHA-256: {hashlib.sha256(source.read_bytes()).hexdigest()}",
             "-/", "", "namespace Queens.Finite.Data", "",
             "set_option maxRecDepth 2048", ""]
    tree_lines, tree = balanced_tree(entries, "(ℕ × WindowBound)", "windowBoundTree_")
    lines += tree_lines
    lines += ["/-- Proposition 24: the proposed window bounds, stored in a balanced tree "
              "keyed by the encoded vertex. -/",
              "def windowBounds : BinaryTree (ℕ × WindowBound) :=", "  " + tree, "",
              "end Queens.Finite.Data", ""]
    output = ROOT / "Queens" / "Finite" / "WindowData.lean"
    write_lean(output, "\n".join(lines))
    print(f"Wrote {output.relative_to(ROOT)}: window bounds for {len(entries)} vertices")

    check_lines = ["import Queens.Finite.WindowChecks", "", "/-!",
                   "# Bounded kernel checks of the window bounds at the vertices",
                   "",
                   "Generated by `python3 scripts/export_window_bounds.py`; do not edit by hand.",
                   "Each proof checks at most 64 entries of the window-bound tree or of",
                   "the history-graph tree. Separating the checks bounds the Lean",
                   "kernel's reduction cache; no entry is omitted.",
                   "-/", "", "namespace Queens.Finite", "",
                   "set_option Elab.async false",
                   "set_option maxRecDepth 100000",
                   "set_option maxHeartbeats 20000000", ""]
    bounds_root = indexed_checks(check_lines, len(entries), "Data.windowBounds",
                                 "checkWindowVertex", "checkedWindowVertices_")
    graph_root = indexed_checks(check_lines, len(vertices), "Data.historyGraph.tree",
                                "hasWindowBound", "checkedGraphVertices_")
    check_lines += [
        "/-- Proposition 24: every entry of the window-bound tree passes",
        "`checkWindowVertex`. Each bounded check is verified by Lean's kernel. -/",
        "theorem windowVertices_checked :",
        "    indexedAll checkWindowVertex Data.windowBounds = true :=",
        f"  {bounds_root}", "",
        "/-- Section 6.6: every vertex of the history graph has window bounds.",
        "Each bounded check is verified by Lean's kernel. -/",
        "theorem graphVertices_checked :",
        "    indexedAll hasWindowBound Data.historyGraph.tree = true :=",
        f"  {graph_root}", "",
        "end Queens.Finite", ""]
    check_output = ROOT / "Queens" / "Finite" / "WindowVertexChecks.lean"
    write_lean(check_output, "\n".join(check_lines))
    print(f"Wrote {check_output.relative_to(ROOT)}: bounded checks of "
          f"{len(entries)} window bounds and {len(vertices)} graph vertices")


if __name__ == "__main__":
    main()
