#!/usr/bin/env python3
"""Export candidate invariant data for Proposition 17, without exporting proofs.

Run from any directory. The reference tuple calculation supplies the candidate
states; Lean independently checks the history graph and recomputes *all* local
successors. Thus this exporter and its Python dependencies are not part of the
trusted proof base. The output is deterministic and records its source digest.
"""
from __future__ import annotations

from collections import deque
import hashlib
import json
from pathlib import Path
import sys

from lean_export import balanced_tree, write_lean

ROOT = Path(__file__).resolve().parents[1]
REFERENCE = ROOT / "queens-formalization-kit" / "companion" / "verification"
sys.path.insert(0, str(REFERENCE))
from calculation import HistoryGraph, encode  # noqa: E402
from verify_tuples import explore  # noqa: E402


def record(state):
    mask = lambda offsets: sum(1 << x for x in offsets)
    return (state.w, state.z, mask(state.R), mask(state.D), mask(state.A),
            encode(state.H_in), tuple(state.Q), encode(state.H_out))


def chunks(name, entries, entry_type, size=64):
    lines = []
    names = []
    for offset in range(0, len(entries), size):
        chunk = f"{name}_{offset // size}"
        names.append(chunk)
        lines += [f"private def {chunk} : List {entry_type} := [",
                  ",\n".join("  " + entry for entry in entries[offset:offset + size]), "]", ""]
    return lines, names


def main():
    source = REFERENCE / "history.json"
    graph = HistoryGraph.load(source)
    initial, successors, _stats = explore(graph)
    states = sorted(record(state) for state in successors)
    vertices = sorted(json.loads(source.read_text())["vertices"])
    lines = ["import Queens.Finite.StateIndex", "", "/-!",
             "# Generated finite certificate data",
             "",
             "Candidate invariant for Proposition 17 (Section 6.3).",
             "Generated by `scripts/export_finite_certificate.py`; do not edit by hand.",
             "No graph edges or success claims are accepted from Python: the Lean",
             "checker recomputes every successor using `calculate`.",
             f"Source history.json SHA-256: {hashlib.sha256(source.read_bytes()).hexdigest()}",
             "-/", "", "namespace Queens.Finite.Data", "",
             "set_option maxRecDepth 2048", ""]
    history_lines, tree = balanced_tree(
        [f"({vertex}, {mask})" for vertex, mask in vertices],
        "(ℕ × ℕ)", "historyTree_")
    lines += history_lines
    lines += ["/-- Definition 11 and Section 6.2: the supplied twelve-symbol history graph, stored in a balanced tree for kernel evaluation. -/",
              "def historyGraph : HistoryGraph :=", "  ⟨" + tree + "⟩", ""]
    entries = []
    for w, z, R, D, A, hin, queue, hout in states:
        entries.append(f"⟨{w}, {z}, {R}, {D}, {A}, {hin}, decode {encode(queue)} {len(queue)}, {hout}⟩")
    state_lines, state_names = chunks("stateChunk", entries, "State")
    lines += state_lines
    tree_lines, state_tree = balanced_tree(
        [f"({i}, {entry})" for i, entry in enumerate(entries)],
        "(ℕ × State)", "stateIndexTree_")
    lines += tree_lines
    lines += ["/-- Proposition 17: the proposed balanced state index; its agreement with the invariant table is checked in Lean. -/",
              "def stateIndex : BinaryTree (ℕ × State) :=", "  " + state_tree, ""]
    lines += ["/-- Proposition 17: bounded chunks of the candidate invariant, allowing separate kernel checks. -/",
              "def stateChunks : Array (List State) :=", "  #[" + ", ".join(state_names) + "]", "",
              "/-- Proposition 17: the candidate closed invariant, sorted by all eight fields. -/",
              "def states : Array State :=", "  stateChunks.toList.flatten.toArray", "",
              "end Queens.Finite.Data", ""]
    output = ROOT / "Queens" / "Finite" / "Data.lean"
    write_lean(output, "\n".join(lines))
    print(f"Wrote {output.relative_to(ROOT)}: {len(vertices)} history vertices, {len(states)} states")
    print(f"Initial state index: {states.index(record(initial))}")

    # A separate, untrusted predecessor tree witnesses that every invariant
    # entry is actually reachable. Lean validates the distances and every edge.
    index = {state: i for i, state in enumerate(states)}
    distance = {initial: 0}
    parent = {initial: initial}
    pending = deque([initial])
    while pending:
        state = pending.popleft()
        for successor in sorted(successors[state], key=record):
            if successor not in distance:
                distance[successor] = distance[state] + 1
                parent[successor] = state
                pending.append(successor)
    assert len(distance) == len(states)
    by_record = {record(state): state for state in successors}
    witnesses = [(distance[by_record[state]], index[record(parent[by_record[state]])])
                 for state in states]
    reach_lines = ["import Queens.Finite.Data", "", "/-!",
                   "# Generated reachability witnesses",
                   "",
                   "Proposition 17, Section 6.3: candidate distances and predecessor indices.",
                   "Generated by `scripts/export_finite_certificate.py`; do not edit by hand.",
                   "Every predecessor edge and strict distance decrease is checked in Lean.",
                   "The safety invariant does not depend on these additional witnesses.",
                   "-/", "", "namespace Queens.Finite.Data", "",
                   "set_option maxRecDepth 2048", ""]
    witness_lines, witness_names = chunks("predecessorChunk",
        [f"({depth}, {pred})" for depth, pred in witnesses], "(ℕ × ℕ)")
    reach_lines += witness_lines
    tree_lines, predecessor_tree = balanced_tree(
        [f"({i}, ({depth}, {parent}))" for i, (depth, parent) in enumerate(witnesses)],
        "(ℕ × (ℕ × ℕ))", "predecessorTree_")
    reach_lines += tree_lines
    reach_lines += ["/-- Proposition 17: a balanced index for the auxiliary predecessor records, checked against the original array in Lean. -/",
                    "def predecessorIndex : BinaryTree (ℕ × (ℕ × ℕ)) :=",
                    "  " + predecessor_tree, ""]
    reach_lines += ["/-- Proposition 17: candidate distance and predecessor for each state-table index. -/",
                    "def predecessors : Array (ℕ × ℕ) :=",
                    "  ([" + ", ".join(witness_names) + "].flatten).toArray", "",
                    "end Queens.Finite.Data", ""]
    reach_output = ROOT / "Queens" / "Finite" / "ReachabilityData.lean"
    write_lean(reach_output, "\n".join(reach_lines))
    print(f"Wrote {reach_output.relative_to(ROOT)}: {len(witnesses)} predecessor witnesses; "
          f"maximum distance {max(distance.values())}")


if __name__ == "__main__":
    main()
