#!/usr/bin/env python3
"""Export untrusted forty-symbol graph data for Corollary 19 (Section 6.5).

The reference construction is repeated from its defining greedy prefix. Nothing
is written into the supplied kit. Lean checks the generated history graph,
recomputes every state transition, and checks exact indexed successor sets.
State numbering agrees with companion/oeis/graphs.py: the initial state first,
then the insertion order of the reference exploration. No Python result is a
substitute for a Lean theorem.
"""
from __future__ import annotations

import hashlib
import json
from pathlib import Path
import sys

from lean_export import balanced_tree, indexed_checks, write_lean

ROOT = Path(__file__).resolve().parents[1]
REFERENCE = ROOT.parent / "verification"
sys.path.insert(0, str(REFERENCE))
from calculation import encode  # noqa: E402
from construct_history_graph import construct  # noqa: E402
from verify_tuples import explore  # noqa: E402
from export_finite_certificate import record  # noqa: E402


def build_data():
    """Return the history graph, reference-numbered states, and indexed adjacency."""
    history = construct(memory=40, start=80)["graph"]
    initial, transitions, statistics = explore(history, 80)
    states = [initial] + [state for state in transitions if state != initial]
    number = {state: i for i, state in enumerate(states)}
    adjacency = [sorted(number[target] for target in transitions[state]) for state in states]
    sizes = (history.vertex_count(), history.edge_count(), len(states), sum(map(len, adjacency)))
    if sizes != (16876, 17499, 29267, 30000) or statistics.stopped_branches:
        raise RuntimeError(f"Unexpected forty-symbol graph: {sizes}")
    return history, states, adjacency


def lean_state(state):
    w, z, rows, diagonals, antidiagonals, hin, queue, hout = record(state)
    return (f"⟨{w}, {z}, {rows}, {diagonals}, {antidiagonals}, {hin}, "
            f"decode {encode(queue)} {len(queue)}, {hout}⟩")


def export_history_checks(vertices):
    """Split kernel reduction into small opaque subtree certificates."""
    lines = ["import Queens.Finite.FortyData", "import Queens.Finite.HistoryChecking", "",
             "/-!", "# Generated kernel checks for the forty-symbol history graph", "",
             "Corollary 19: each bounded subtree is checked by the Lean kernel.",
             "Opaque intermediate lemmas limit the reduction cache; their conjunction",
             "proves the same complete bound, uniqueness, and edge-closure check.",
             "Generated by `scripts/export_forty_certificate.py`; do not edit by hand.",
             "-/", "", "namespace Queens.Finite.Forty", "",
             "set_option maxRecDepth 100000", "set_option maxHeartbeats 0",
             "set_option Elab.async false", ""]
    number = 0

    def emit(entries, path, lo, hi):
        nonlocal number
        left = right = None
        if len(entries) > 64:
            middle = len(entries) // 2
            key = entries[middle][0]
            left = emit(entries[:middle], path + ".left", lo, key)
            right = emit(entries[middle + 1:], path + ".right", key + 1, hi)
        name = f"historyPart_{number}"
        number += 1
        lines.extend([f"private theorem {name} :",
                      f"    checkHistoryBounds {lo} {hi} ({path}) = true ∧",
                      f"      historyAll (checkHistoryEntry FortyData.historyGraph 40) ({path}) = true := by"])
        if left is None:
            lines.append("  decide +kernel")
        else:
            lines.extend(["  constructor",
                          "  · exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr",
                          f"      ⟨by decide +kernel, {left}.1⟩, {right}.1⟩",
                          "  · exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr",
                          f"      ⟨by decide +kernel, {left}.2⟩, {right}.2⟩"])
        lines.append("")
        return name

    root = emit(vertices, "FortyData.historyGraph.tree", 0, 4 ** 40)
    lines.extend(["/-- Corollary 19: kernel verification of the complete forty-symbol history",
                  "graph, assembled from independently checked bounded subtrees. -/",
                  "theorem historyGraph_checked : checkHistoryGraph FortyData.historyGraph 40 = true :=",
                  f"  Bool.and_eq_true_iff.mpr {root}", "", "end Queens.Finite.Forty", ""])
    path = ROOT / "Queens" / "Finite" / "FortyHistoryChecks.lean"
    write_lean(path, "\n".join(lines))
    print(f"Wrote {path.relative_to(ROOT)}: {number} kernel-check lemmas")


def vertex_tree(states, adjacency):
    """One canonical indexed table stores both states and outgoing indices."""
    entries = [f"({i}, ({lean_state(state)}, [{', '.join(map(str, targets))}]))"
               for i, (state, targets) in enumerate(zip(states, adjacency, strict=True))]
    return balanced_tree(entries, "(ℕ × (State × List ℕ))", "vertexTreeChunk_")


def export_state_checks(count, assembly_path=None):
    """Check four independent quarters, with bounded sequential leaf checks.

    Lake may compile the four modules concurrently. The assembly also checks
    the three nodes above the quarters, so no state is omitted by partitioning.
    """
    prefix = ["/-!", "# Generated kernel checks for the forty-symbol state invariant", "",
              "Corollary 19: each subtree checks every branch of every listed state.",
              "The opaque intermediate proofs bound kernel reduction memory; all are",
              "ordinary kernel proofs, with no compiler-evaluation axiom.",
              "Generated by `scripts/export_forty_certificate.py`; do not edit by hand.",
              "-/", "", "namespace Queens.Finite.Forty", "",
              "set_option maxRecDepth 100000", "set_option maxHeartbeats 0",
              "set_option Elab.async false", ""]

    left_size = count // 2
    right_size = count - left_size - 1
    quarters = [(left_size // 2, ".left.left"),
                (left_size - left_size // 2 - 1, ".left.right"),
                (right_size // 2, ".right.left"),
                (right_size - right_size // 2 - 1, ".right.right")]
    for quarter, (size, path) in enumerate(quarters):
        lines = ["import Queens.Finite.FortyTable", ""] + prefix
        root = indexed_checks(lines, size, "FortyData.vertexTable" + path,
                              "checkVertexEntry", "statePart_")
        lines.extend([f"/-- Corollary 19: kernel verification of quarter {quarter + 1} of the",
                      "forty-symbol state table, including every outgoing branch. -/",
                      f"theorem vertexQuarter{quarter}_checked :",
                      f"    indexedAll checkVertexEntry (FortyData.vertexTable{path}) = true :=",
                      f"  {root}", "", "end Queens.Finite.Forty", ""])
        output = ROOT / "Queens" / "Finite" / f"FortyStateChecksPart{quarter}.lean"
        write_lean(output, "\n".join(lines))
        print(f"Wrote {output.relative_to(ROOT)}: {size} states")

    lines = [f"import Queens.Finite.FortyStateChecksPart{i}" for i in range(4)] + [""] + prefix
    for name, path, left, right in [
            ("leftHalf_checked", ".left", "vertexQuarter0_checked", "vertexQuarter1_checked"),
            ("rightHalf_checked", ".right", "vertexQuarter2_checked", "vertexQuarter3_checked")]:
        lines.extend([f"private theorem {name} :",
                      f"    indexedAll checkVertexEntry (FortyData.vertexTable{path}) = true := by",
                      "  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr",
                      f"    ⟨by decide +kernel, {left}⟩, {right}⟩", ""])
    lines.extend(["/-- Corollary 19: kernel verification of every state and every outgoing",
                  "branch. Four independent quarter proofs and all three intervening nodes",
                  "cover the complete tree; each finite check is reduced by the kernel. -/",
                  "theorem vertexTable_checked : indexedAll checkVertexEntry FortyData.vertexTable = true := by",
                  "  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr",
                  "    ⟨by decide +kernel, leftHalf_checked⟩, rightHalf_checked⟩",
                  "", "end Queens.Finite.Forty", ""])
    output = assembly_path or ROOT / "Queens" / "Finite" / "FortyStateChecks.lean"
    write_lean(output, "\n".join(lines))
    print(f"Wrote assembly: {output}")


def main():
    graph, states, adjacency = build_data()
    vertices = sorted((encode(word), sum(1 << symbol for symbol in symbols))
                      for word, symbols in graph.edges.items())
    digest = hashlib.sha256(json.dumps(vertices, separators=(",", ":")).encode()).hexdigest()
    lines = ["import Queens.Finite.Local", "import Queens.Finite.IndexedTree", "",
             "/-!", "# Generated forty-symbol certificate data",
             "", "Corollary 19, Section 6.5: candidate history and state graphs.",
             "Generated by `scripts/export_forty_certificate.py`; do not edit by hand.",
             "The Lean checker recomputes every successor, including every branch.",
             "State indices agree with the reference `oeis/graphs.py` numbering.",
             "Canonical history-vertex JSON SHA-256:", f"{digest}", "-/", "",
             "namespace Queens.Finite.FortyData", "", "set_option maxRecDepth 100000", ""]
    history_lines, root = balanced_tree(
        [f"({vertex}, {mask})" for vertex, mask in vertices],
        "(ℕ × ℕ)", "historyTreeChunk_")
    lines += history_lines
    lines += ["/-- Corollary 19: the balanced candidate forty-symbol history graph. -/",
              "def historyGraph : HistoryGraph :=", f"  ⟨{root}⟩", ""]
    vertex_lines, vertices_root = vertex_tree(states, adjacency)
    lines += vertex_lines
    lines += ["/-- Corollary 19: the canonical balanced table of indices, states, and outgoing indices. -/",
              "def vertexTable : BinaryTree (ℕ × (State × List ℕ)) :=", f"  {vertices_root}", "",
              "/-- Corollary 19: candidate states in reference order, with the column-80 seed at index zero. -/",
              "def states : Array State :=",
              "  ((indexedEntries vertexTable).map (fun entry => entry.2.1)).toArray", "",
              "/-- Corollary 19: candidate adjacency, projected from the same canonical table. -/",
              "def successors : Array (List ℕ) :=",
              "  ((indexedEntries vertexTable).map (fun entry => entry.2.2)).toArray", ""]
    lines += ["/-- Corollary 19: the proposed actual local state immediately before column 80. -/",
              "def initialState : State :=", "  " + lean_state(states[0]), "",
              "end Queens.Finite.FortyData", ""]
    path = ROOT / "Queens" / "Finite" / "FortyData.lean"
    write_lean(path, "\n".join(lines))
    print(f"Wrote {path.relative_to(ROOT)}: {len(vertices)} history vertices, "
          f"{len(states)} states, {sum(map(len, adjacency))} state edges")
    export_history_checks(vertices)
    export_state_checks(len(states))


if __name__ == "__main__":
    main()
