#!/usr/bin/env python3
"""Generate the finite E_c(v) run-length certificate for Corollary 19.

The Lean checker verifies the closure and boundary conditions; this script's
path enumeration is not trusted. Vertex numbers agree with FortyData.
"""
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT.parent / "oeis"))
import graphs
from export_forty_certificate import build_data
from lean_export import balanced_tree, indexed_checks, write_lean


def possible_lengths(runs: dict[int, set[tuple[int, int]]], label: int):
    order = graphs.topological_order(set(runs),
        lambda v: {t for t, c in runs[v] if c == label})
    if order is None:
        raise ValueError("constant-label cycle")
    lengths = {}
    for v in reversed(order):
        values = {0} if any(c != label for _, c in runs[v]) else set()
        for t, c in runs[v]:
            if c == label:
                values.update(k + 1 for k in lengths[t])
        lengths[v] = sorted(values)
    return lengths


def export_checks(count: int) -> None:
    """Emit sequential bounded proofs, mirroring the balanced layout exactly."""
    lines = ["import Queens.Finite.RepeatedRunDefinitions", "", "/-!",
             "# Generated kernel checks for the Corollary 19 run graph", "",
             "Every lookup and closure obligation is checked on a subtree of at most",
             "64 vertices, then assembled by Boolean conjunction. The two alignment",
             "checks compare the complete mathematical lists. No compiler evaluation",
             "axiom is used. Generated by `scripts/export_run_lengths.py`.", "-/", "",
             "namespace Queens.Finite", "", "set_option maxRecDepth 200000",
             "set_option maxHeartbeats 0", "set_option Elab.async false", ""]
    predicates = [
        ("lookup", "fun e => decide (indexedLookup e.1 repeatedRunTree = some e.2)",
         "repeatedRunTree_self_lookup", "Corollary 19: every proposed key resolves to its exact stored payload."),
        ("closure", "fun e => decide (e.2.upper = true → CheckRepeatedRunVertex e.1)",
         "repeatedRunLengthData_checked", "Corollary 19: every run-length closure and boundary obligation is kernel-checked."),
    ]
    for prefix, predicate, public_name, doc in predicates:
        root = indexed_checks(lines, count, "repeatedRunTree", f"({predicate})", f"{prefix}Part_")
        lines.extend([f"/-- {doc} -/", f"theorem {public_name} :",
                      f"    indexedAll ({predicate}) repeatedRunTree = true := {root}", ""])
    lines.extend([
        "/-- Corollary 19: the proposed upper bits agree with the original forty-symbol states. -/",
        "theorem repeatedRunTree_upper_alignment :",
        "    (indexedEntries repeatedRunTree).map (fun e => (e.1, e.2.upper)) =",
        "      (FortyData.states.toList.map (fun s => decide (upperBit (s.output % 4) = 1))).zipIdx.map",
        "        Prod.swap := by", "  decide +kernel", "",
        "/-- Corollary 19: proposed adjacency is exactly the original forty-symbol adjacency. -/",
        "theorem repeatedRunTree_successor_alignment :",
        "    (indexedEntries repeatedRunTree).map (fun e => (e.1, e.2.successors)) =",
        "      FortyData.successors.toList.zipIdx.map Prod.swap := by", "  decide +kernel", "",
        "end Queens.Finite", ""])
    write_lean(ROOT / "Queens/Finite/RepeatedRunChecks.lean", "\n".join(lines))


def main() -> None:
    history, states, adjacency = build_data()
    # Use the reference contractor, with exactly the exported state numbering.
    out = [[(t, states[t].H_out[-1]) for t in dest] for dest in adjacency]
    graph = graphs.StateGraph(40, 80, history, states, out, None)
    runs = graphs.run_graph(graphs.gap_graph(graph))
    lengths = [possible_lengths(runs, c) for c in (1, 2, 3)]
    payloads = []
    for v, state in enumerate(states):
        entries = ["[" + ", ".join(map(str, data.get(v, []))) + "]" for data in lengths]
        upper = "true" if state.H_out[-1] // 2 else "false"
        successors = "[" + ", ".join(map(str, adjacency[v])) + "]"
        payloads.append(f"⟨{upper}, {successors}, " + ", ".join(entries) + "⟩")
    lines, root = balanced_tree(
        [f"({i}, {payload})" for i, payload in enumerate(payloads)],
        "(ℕ × RunVertexData)", "runTreeChunk", chunk_size=63)
    text = '''import Queens.Finite.FortyData
import Queens.Finite.RunVertex

/-!
# Run-length certificate data for Corollary 19

Generated by `scripts/export_run_lengths.py`. Vertex numbers agree with
`FortyData`. Upper bits and adjacency are checked against that original graph;
remaining-length proposals are checked by `RepeatedRunCertificate.lean`.
-/

namespace Queens.Finite

set_option maxRecDepth 2048

''' + "\n".join(lines)
    text += '''/-- Corollary 19: balanced lookup layout for the run-graph certificate,
using the reference numbering of the forty-symbol state graph. -/
def repeatedRunTree : BinaryTree (ℕ × RunVertexData) :=
  ''' + root + "\n\nend Queens.Finite\n"
    write_lean(ROOT / "Queens/Finite/RepeatedRunData.lean", text)
    export_checks(len(states))



if __name__ == "__main__":
    main()
