#!/usr/bin/env python3
"""Emit bounded Lean kernel proofs for the generated state chunks.

This generator supplies proof scripts, not trusted mathematical facts. Lean
recomputes every predicate using `decide +kernel`; the final theorem assembles
the individually checked chunks with the generic flattening lemma.
"""
from pathlib import Path
import re

from lean_export import write_lean

ROOT = Path(__file__).resolve().parents[1]


def emit(count, module, dependency, predicate, theorem, result):
    lines = [
        f"import Queens.Finite.{dependency}",
        "import Mathlib.Tactic.FinCases",
        "",
        "/-!",
        "# Bounded kernel checks for the local invariant" if result == "Proposition 17"
        else f"# Bounded kernel checks for {result}",
        "",
        "Generated by `scripts/export_kernel_checks.py`; do not edit by hand.",
        "Each proof independently recomputes at most 64 states of Proposition 17."
        if result == "Proposition 17" else
        f"Each proof independently recomputes at most 64 states for {result}.",
        "The checker propagates every failure and validates every successor."
        if result == "Proposition 17" else
        "Every failure rejects the complete check; no branch is discarded.",
        "Separating the checks bounds the Lean kernel's reduction cache.",
        "-/",
        "",
        "namespace Queens.Finite",
        "",
        "set_option Elab.async false",
        "set_option maxRecDepth 100000",
        "set_option maxHeartbeats 20000000",
        "",
    ]
    for i in range(count):
        lines += [
            f"private theorem checkedChunk_{i} :",
            f"    (Data.stateChunks[{i}]!).all {predicate} = true := by",
            "  decide +kernel",
            "",
        ]
    lines += [
        "private theorem all_chunks_checked :",
        f"    ∀ i : Fin {count}, (Data.stateChunks[i.val]!).all {predicate} = true := by",
        "  intro i",
        "  fin_cases i",
    ]
    lines += [f"  · exact checkedChunk_{i}" for i in range(count)]
    lines += [
        "",
        f"/-- {result}: every state in the candidate invariant satisfies the",
        "independently recomputed check. Each bounded check is verified by Lean's",
        "kernel; the final assembly covers every state in the original table. -/",
        f"theorem {theorem} : Data.states.all {predicate} = true := by",
        "  apply all_flatten_of_all_chunks",
        "  intro i",
        f"  have hi : i.val < {count} := i.isLt",
        "  simpa only [getElem!_pos Data.stateChunks i.val i.isLt] using all_chunks_checked ⟨i.val, hi⟩",
        "",
        "end Queens.Finite",
        "",
    ]
    destination = ROOT / f"Queens/Finite/{module}.lean"
    write_lean(destination, "\n".join(lines))
    print(f"Generated {count} bounded kernel checks in {destination.relative_to(ROOT)}")


def emit_counts(count):
    from export_finite_certificate import HistoryGraph, REFERENCE, explore, record

    _, successors, _ = explore(HistoryGraph.load(REFERENCE / "history.json"))
    by_record = {record(state): len(next_states) for state, next_states in successors.items()}
    states = sorted(by_record)
    totals = [sum(by_record[state] for state in states[offset:offset + 64])
              for offset in range(0, len(states), 64)]
    assert len(totals) == count
    lines = [
        "import Queens.Finite.StateCountCore", "import Mathlib.Tactic.FinCases", "", "/-!",
        "# Bounded kernel checks of the edge count", "",
        "Generated by `scripts/export_kernel_checks.py`; do not edit by hand.",
        "Python supplies candidate partial sums; every sum is recomputed by the",
        "Lean kernel from Algorithm 1, with duplicate successors removed.",
        "-/", "", "namespace Queens.Finite", "",
        "set_option Elab.async false", "set_option maxRecDepth 100000",
        "set_option maxHeartbeats 20000000", "",
        f"private def expectedChunkCounts (i : Fin {count}) : ℕ :=",
        "  #[" + ", ".join(map(str, totals)) + "][i.val]!", "",
    ]
    for i, total in enumerate(totals):
        lines += [f"private theorem countChunk_{i} :",
                  f"    ((Data.stateChunks[{i}]!).map stateSuccessorCount).sum = {total} := by",
                  "  decide +kernel", ""]
    lines += ["private theorem all_chunk_counts :",
              f"    ∀ i : Fin {count}, ((Data.stateChunks[i.val]!).map stateSuccessorCount).sum =",
              "      expectedChunkCounts i := by", "  intro i", "  fin_cases i"]
    lines += [f"  · exact countChunk_{i}" for i in range(count)]
    lines += ["", "/-- Proposition 17: recomputing all distinct-successor sets gives 8327 edges.",
              "Each partial count is independently verified by the Lean kernel. -/",
              "theorem state_edge_count : stateEdgeCount = 8327 := by",
              "  change (Data.stateChunks.toList.flatten.map stateSuccessorCount).sum = 8327",
              "  rw [sum_flatten_eq_sum_ofFn]",
              "  have hcounts : (fun i : Fin Data.stateChunks.size =>",
              "      (Data.stateChunks[i.val].map stateSuccessorCount).sum) = expectedChunkCounts := by",
              "    funext i",
              "    simpa only [getElem!_pos Data.stateChunks i.val i.isLt] using all_chunk_counts i",
              "  rw [hcounts]", "  decide +kernel", "", "end Queens.Finite", ""]
    destination = ROOT / "Queens/Finite/StateCounts.lean"
    write_lean(destination, "\n".join(lines))
    print(f"Generated {count} partial edge counts in {destination.relative_to(ROOT)}")


def main():
    source = (ROOT / "Queens/Finite/Data.lean").read_text()
    count = len(re.findall(r"private def stateChunk_\d+ :", source))
    emit(count, "CertificateChunks", "CertificateCore", "checkState",
         "certificate_checked", "Proposition 17")
    emit(count, "SharpChunks", "SharpChecks", "checkSharpState",
         "sharp_certificate_checked", "Proposition 21")
    emit(count, "ReachabilityChunks", "ReachabilityCore", "checkParentState",
         "predecessor_states_checked", "Proposition 17")
    emit_counts(count)


if __name__ == "__main__":
    main()
