#!/usr/bin/env python3
"""Emit finite greedy-row data for Corollary 19; Lean checks every greedy step.

This script only supplies certificate data. The proof of the bitboard checker is
in Queens/Finite/GreedyPrefix.lean, and its application to these data is in
Queens/Finite/RunWitnesses.lean. No Python assertion is imported as a theorem.
"""
from pathlib import Path

from lean_export import balanced_tree, write_lean

ROOT = Path(__file__).resolve().parents[1]
COUNT = 5000


def queens(count: int) -> list[int]:
    rows = rising = falling = 0
    result = []
    for _ in range(count):
        attacked = rows | rising | falling
        queen = (attacked + 1) & ~attacked
        result.append(queen.bit_length() - 1)
        rows |= queen
        rising = (rising | queen) << 1
        falling = (falling | queen) >> 1
    return result


def main() -> None:
    data = queens(COUNT)
    lines = ["  " + ", ".join(map(str, data[i:i + 16])) for i in range(0, COUNT, 16)]
    body = ",\n".join(lines)
    text = '''import Queens.Finite.GreedyPrefix

/-!
# Actual-prefix data for Corollary 19

Generated by `scripts/export_run_witnesses.py`. These are proposed rows only;
`RunWitnesses.lean` verifies them against the original greedy rule.
-/

namespace Queens.Finite

set_option maxRecDepth 100000

/-- Corollary 19: a proposed greedy prefix long enough to witness every value
in the five-row table. Its correctness is proved in `RunWitnesses.lean`. -/
def runWitnessRows : List ℕ :=
[''' + body.lstrip() + ''']

end Queens.Finite
'''
    intervals = []
    start = None
    for n, row in enumerate(data):
        if row < n:
            if start is None:
                start = n
        elif start is not None:
            intervals.append((start, n))
            start = None
    intervals = intervals[:1100]
    def tree_definition(name, values, value_type):
        lines, root = balanced_tree(
            [f"({i}, {value})" for i, value in enumerate(values)],
            f"(ℕ × {value_type})", f"{name}Chunk", chunk_size=63)
        lines.append(f"/-- Corollary 19: balanced lookup layout for the finite witness data. -/\ndef {name} : BinaryTree (ℕ × {value_type}) :=\n  {root}\n")
        return "\n".join(lines)
    trees = tree_definition("runWitnessRowTree", list(map(str, data)), "ℕ")
    trees += tree_definition("lowerRunWitnessIntervalTree", [f"({a}, {b})" for a, b in intervals], "(ℕ × ℕ)")
    text = text.replace("import Queens.Finite.GreedyPrefix", "import Queens.Finite.GreedyPrefix\nimport Queens.Finite.IndexedTree")
    text = text.replace("end Queens.Finite\n", trees + "\nend Queens.Finite\n")
    write_lean(ROOT / "Queens/Finite/RunWitnessData.lean", text)


if __name__ == "__main__":
    main()
