"""Write build/records.h for Spire: the 300 paused records of Section 7.3, as C tables.

Spire starts a copy of the calculation anywhere by finding its paused record from the input
symbols just before that point (the records inconsistent with them drop out), and reads the
copy's counters off the record. This script writes what that needs, for each record: w, z,
|D| and |Q|, its successor on each input symbol, and the table position (row offset in
../fast_generator/generated/tables.h) of its class.

It also checks, along the first 2^21 symbols of the queen word, the formulas Spire relies on.
At every byte boundary, with p the input position (the index of the next symbol read),

    m = p - |Q|,    n = m + U(m-1) + z,    U(n-1) = m + w - |D|,

where n is the column, m the least unused row, and U(x) the number of upper columns among
1 .. x. The record at each boundary comes from following the record graph from the start,
and the counters from following the table.

    python3 make_records.py [output]
"""
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
GENERATED = os.path.join(HERE, '..', 'fast_generator', 'generated')

records = json.load(open(os.path.join(GENERATED, 'paused_records.json')))
assert records['state_format'] == ['w', 'z', 'R', 'D', 'A', 'past4_newest_low', 'Q']
states = records['states']
successor = {(a, s): b for a, s, b, _ in records['edges']}

text = open(os.path.join(GENERATED, 'tables.h')).read()
def define(name):
    return int(re.search(r'#define %s (\d+)' % name, text).group(1))
def array(name):
    body = re.search(r'%s\[\d+\] = \{(.*?)\};' % name, text, re.S).group(1)
    return [int(x) for x in re.findall(r'UINT64_C\((\d+)\)', body)] or [int(x) for x in re.findall(r'\d+', body)]
table, packets, seed = array('qf_table'), array('qf_packets'), array('qf_seed_queens')
INITIAL_STATE, INITIAL_PACKET = define('QF_INITIAL_STATE'), define('QF_INITIAL_PACKET')
INITIAL_M, INITIAL_UPPER, INITIAL_LENGTH = define('QF_INITIAL_M'), define('QF_INITIAL_UPPER'), define('QF_INITIAL_LENGTH')
INITIAL_SYMBOLS = int(re.search(r'#define QF_INITIAL_SYMBOLS UINT64_C\((\d+)\)', text).group(1))

def entry(position, byte):
    e = table[position + byte]
    return e & 4095, (e >> 12) & 15, (e >> 16) & 0xFFFFFF, e >> 40  # next, length, symbols, packet

# sigma_30, sigma_31, ...: the queen word, made by one copy reading its own output.
LENGTH = 1 << 21
sigma = [(INITIAL_SYMBOLS >> (2 * j)) & 3 for j in range(INITIAL_LENGTH)]
position, read = INITIAL_STATE, 0
while len(sigma) < LENGTH + 64:
    byte = sigma[read] | sigma[read + 1] << 2 | sigma[read + 2] << 4 | sigma[read + 3] << 6
    read += 4
    position, length, symbols, _ = entry(position, byte)
    sigma.extend((symbols >> (2 * j)) & 3 for j in range(length))

# U(x) for x < 30 + LENGTH.
upper_before = [0] * (30 + LENGTH)
for x in range(1, len(upper_before)):
    upper = seed[x] > x if x < 30 else sigma[x - 30] >> 1
    upper_before[x] = upper_before[x - 1] + upper

# Along the word: the record (by the record graph, from the pause before column 48) and the
# table position and counters (by the table), at every byte boundary.
block = packets[INITIAL_PACKET:]
column, m, U = 48, INITIAL_M + block[1], INITIAL_UPPER + block[2]
position, record = INITIAL_STATE, 0
record_class = {}
for k in range(LENGTH // 4 - 16):
    p = 30 + 4 * k
    w, z, R, D, A, past4, Q = states[record]
    assert m == p - len(Q), ('m', p)
    assert U == m + w - bin(D).count('1'), ('U', p)
    assert column == m + upper_before[m - 1] + z, ('n', p)
    assert record_class.setdefault(record, position) == position, ('class', p)
    byte = sigma[4 * k] | sigma[4 * k + 1] << 2 | sigma[4 * k + 2] << 4 | sigma[4 * k + 3] << 6
    nxt, _, _, packet = entry(position, byte)
    column += packets[packet]; m += packets[packet + 1]; U += packets[packet + 2]
    position = nxt
    for s in sigma[4 * k: 4 * k + 4]:
        record = successor[(record, s)]

# Every record's table position. A copy's table position is the class of its current record
# (Section 7.3), so the records met above show where each of the 82 classes sits in the table
# (two compatible classes share a position); the classes then place the records never met.
classes = records['mapping_to_82_classes']
class_position = {}
for record, position in record_class.items():
    assert class_position.setdefault(classes[record], position) == position, ('class', record)
assert len(class_position) == len(set(classes)), 'a class never met along the word'
record_position = [class_position[classes[i]] for i in range(len(states))]

output = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, 'build', 'records.h')
os.makedirs(os.path.dirname(output), exist_ok=True)
with open(output, 'w') as f:
    n = len(states)
    f.write('/* Generated by spire/make_records.py: the %d paused records of Section 7.3. */\n' % n)
    f.write('#define REC_COUNT %d\n' % n)
    f.write('static const int8_t rec_w[%d] = {%s};\n' % (n, ','.join(str(s[0]) for s in states)))
    f.write('static const int8_t rec_z[%d] = {%s};\n' % (n, ','.join(str(s[1]) for s in states)))
    f.write('static const uint8_t rec_Dn[%d] = {%s};\n' % (n, ','.join(str(bin(s[3]).count('1')) for s in states)))
    f.write('static const uint8_t rec_Qn[%d] = {%s};\n' % (n, ','.join(str(len(s[6])) for s in states)))
    f.write('static const int16_t rec_next[%d][4] = {%s};\n' % (n, ','.join(
        '{%s}' % ','.join(str(successor.get((i, s), -1)) for s in range(4)) for i in range(n))))
    f.write('static const int16_t rec_base[%d] = {%s};\n' % (n, ','.join(str(p) for p in record_position)))
print('%s: %d records (%d met along %d symbols) in %d classes; the counter formulas hold at %d byte boundaries'
      % (os.path.relpath(output), len(states), len(record_class), LENGTH, len(class_position), LENGTH // 4 - 16))
