import Queens.Finite.FortyStateChecksPart0
import Queens.Finite.FortyStateChecksPart1
import Queens.Finite.FortyStateChecksPart2
import Queens.Finite.FortyStateChecksPart3

/-!
# Generated kernel checks for the forty-symbol state invariant

Corollary 19: each subtree checks every branch of every listed state.
The opaque intermediate proofs bound kernel reduction memory; all are
ordinary kernel proofs, with no compiler-evaluation axiom.
Generated by `scripts/export_forty_certificate.py`; do not edit by hand.
-/

namespace Queens.Finite.Forty

set_option maxRecDepth 100000
set_option Elab.async false

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem leftHalf_checked :
    indexedAll checkVertexEntry (FortyData.vertexTable.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, vertexQuarter0_checked⟩, vertexQuarter1_checked⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem rightHalf_checked :
    indexedAll checkVertexEntry (FortyData.vertexTable.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, vertexQuarter2_checked⟩, vertexQuarter3_checked⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
/-- Corollary 19: kernel verification of every state and every outgoing
branch. Four independent quarter proofs and all three intervening nodes
cover the complete tree; each finite check is reduced by the kernel. -/
theorem vertexTable_checked : indexedAll checkVertexEntry FortyData.vertexTable = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, leftHalf_checked⟩, rightHalf_checked⟩

end Queens.Finite.Forty
