import Queens.Finite.FortyTable

/-!
# Generated kernel checks for the forty-symbol state invariant

Corollary 19: each subtree checks every branch of every listed state.
The opaque intermediate proofs bound kernel reduction memory; all are
ordinary kernel proofs, with no compiler-evaluation axiom.
Generated by `scripts/export_forty_certificate.py`; do not edit by hand.
-/

-- Generated tree literals and check statements preserve the evaluation layout.
set_option linter.style.longLine false
-- The complete generated certificate is kept in deterministic traversal order.
set_option linter.style.longFile 1800

namespace Queens.Finite.Forty

set_option maxRecDepth 100000
set_option Elab.async false

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_0 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.left.left.left.left.left.left) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_1 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.left.left.left.left.left.right) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_2 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.left.left.left.left.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_0⟩, statePart_1⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_3 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.left.left.left.left.right.left) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_4 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.left.left.left.left.right.right) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_5 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.left.left.left.left.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_3⟩, statePart_4⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_6 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.left.left.left.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_2⟩, statePart_5⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_7 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.left.left.left.right.left.left) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_8 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.left.left.left.right.left.right) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_9 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.left.left.left.right.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_7⟩, statePart_8⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_10 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.left.left.left.right.right.left) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_11 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.left.left.left.right.right.right) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_12 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.left.left.left.right.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_10⟩, statePart_11⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_13 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.left.left.left.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_9⟩, statePart_12⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_14 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.left.left.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_6⟩, statePart_13⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_15 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.left.left.right.left.left.left) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_16 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.left.left.right.left.left.right) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_17 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.left.left.right.left.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_15⟩, statePart_16⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_18 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.left.left.right.left.right.left) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_19 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.left.left.right.left.right.right) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_20 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.left.left.right.left.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_18⟩, statePart_19⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_21 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.left.left.right.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_17⟩, statePart_20⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_22 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.left.left.right.right.left.left) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_23 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.left.left.right.right.left.right) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_24 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.left.left.right.right.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_22⟩, statePart_23⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_25 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.left.left.right.right.right.left) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_26 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.left.left.right.right.right.right) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_27 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.left.left.right.right.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_25⟩, statePart_26⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_28 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.left.left.right.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_24⟩, statePart_27⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_29 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.left.left.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_21⟩, statePart_28⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_30 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.left.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_14⟩, statePart_29⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_31 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.left.right.left.left.left.left) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_32 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.left.right.left.left.left.right) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_33 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.left.right.left.left.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_31⟩, statePart_32⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_34 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.left.right.left.left.right.left) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_35 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.left.right.left.left.right.right) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_36 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.left.right.left.left.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_34⟩, statePart_35⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_37 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.left.right.left.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_33⟩, statePart_36⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_38 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.left.right.left.right.left.left) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_39 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.left.right.left.right.left.right) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_40 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.left.right.left.right.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_38⟩, statePart_39⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_41 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.left.right.left.right.right.left) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_42 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.left.right.left.right.right.right) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_43 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.left.right.left.right.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_41⟩, statePart_42⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_44 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.left.right.left.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_40⟩, statePart_43⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_45 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.left.right.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_37⟩, statePart_44⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_46 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.left.right.right.left.left.left) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_47 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.left.right.right.left.left.right) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_48 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.left.right.right.left.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_46⟩, statePart_47⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_49 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.left.right.right.left.right.left) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_50 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.left.right.right.left.right.right) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_51 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.left.right.right.left.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_49⟩, statePart_50⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_52 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.left.right.right.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_48⟩, statePart_51⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_53 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.left.right.right.right.left.left) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_54 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.left.right.right.right.left.right) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_55 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.left.right.right.right.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_53⟩, statePart_54⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_56 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.left.right.right.right.right.left) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_57 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.left.right.right.right.right.right) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_58 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.left.right.right.right.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_56⟩, statePart_57⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_59 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.left.right.right.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_55⟩, statePart_58⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_60 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.left.right.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_52⟩, statePart_59⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_61 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.left.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_45⟩, statePart_60⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_62 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_30⟩, statePart_61⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_63 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.right.left.left.left.left.left) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_64 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.right.left.left.left.left.right) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_65 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.right.left.left.left.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_63⟩, statePart_64⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_66 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.right.left.left.left.right.left) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_67 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.right.left.left.left.right.right) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_68 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.right.left.left.left.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_66⟩, statePart_67⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_69 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.right.left.left.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_65⟩, statePart_68⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_70 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.right.left.left.right.left.left) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_71 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.right.left.left.right.left.right) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_72 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.right.left.left.right.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_70⟩, statePart_71⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_73 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.right.left.left.right.right.left) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_74 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.right.left.left.right.right.right) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_75 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.right.left.left.right.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_73⟩, statePart_74⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_76 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.right.left.left.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_72⟩, statePart_75⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_77 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.right.left.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_69⟩, statePart_76⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_78 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.right.left.right.left.left.left) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_79 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.right.left.right.left.left.right) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_80 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.right.left.right.left.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_78⟩, statePart_79⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_81 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.right.left.right.left.right.left) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_82 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.right.left.right.left.right.right) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_83 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.right.left.right.left.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_81⟩, statePart_82⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_84 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.right.left.right.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_80⟩, statePart_83⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_85 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.right.left.right.right.left.left) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_86 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.right.left.right.right.left.right) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_87 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.right.left.right.right.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_85⟩, statePart_86⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_88 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.right.left.right.right.right.left) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_89 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.right.left.right.right.right.right) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_90 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.right.left.right.right.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_88⟩, statePart_89⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_91 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.right.left.right.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_87⟩, statePart_90⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_92 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.right.left.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_84⟩, statePart_91⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_93 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.right.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_77⟩, statePart_92⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_94 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.right.right.left.left.left.left) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_95 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.right.right.left.left.left.right) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_96 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.right.right.left.left.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_94⟩, statePart_95⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_97 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.right.right.left.left.right.left) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_98 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.right.right.left.left.right.right) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_99 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.right.right.left.left.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_97⟩, statePart_98⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_100 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.right.right.left.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_96⟩, statePart_99⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_101 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.right.right.left.right.left.left) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_102 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.right.right.left.right.left.right) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_103 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.right.right.left.right.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_101⟩, statePart_102⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_104 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.right.right.left.right.right.left) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_105 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.right.right.left.right.right.right) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_106 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.right.right.left.right.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_104⟩, statePart_105⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_107 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.right.right.left.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_103⟩, statePart_106⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_108 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.right.right.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_100⟩, statePart_107⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_109 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.right.right.right.left.left.left) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_110 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.right.right.right.left.left.right) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_111 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.right.right.right.left.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_109⟩, statePart_110⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_112 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.right.right.right.left.right.left) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_113 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.right.right.right.left.right.right) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_114 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.right.right.right.left.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_112⟩, statePart_113⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_115 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.right.right.right.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_111⟩, statePart_114⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_116 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.right.right.right.right.left.left) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_117 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.right.right.right.right.left.right) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_118 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.right.right.right.right.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_116⟩, statePart_117⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_119 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.right.right.right.right.right.left) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_120 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.right.right.right.right.right.right) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_121 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.right.right.right.right.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_119⟩, statePart_120⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_122 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.right.right.right.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_118⟩, statePart_121⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_123 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.right.right.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_115⟩, statePart_122⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_124 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.right.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_108⟩, statePart_123⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_125 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_93⟩, statePart_124⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_126 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_62⟩, statePart_125⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_127 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.left.left.left.left.left.left) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_128 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.left.left.left.left.left.right) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_129 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.left.left.left.left.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_127⟩, statePart_128⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_130 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.left.left.left.left.right.left) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_131 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.left.left.left.left.right.right) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_132 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.left.left.left.left.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_130⟩, statePart_131⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_133 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.left.left.left.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_129⟩, statePart_132⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_134 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.left.left.left.right.left.left) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_135 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.left.left.left.right.left.right) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_136 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.left.left.left.right.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_134⟩, statePart_135⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_137 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.left.left.left.right.right.left) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_138 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.left.left.left.right.right.right) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_139 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.left.left.left.right.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_137⟩, statePart_138⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_140 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.left.left.left.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_136⟩, statePart_139⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_141 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.left.left.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_133⟩, statePart_140⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_142 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.left.left.right.left.left.left) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_143 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.left.left.right.left.left.right) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_144 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.left.left.right.left.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_142⟩, statePart_143⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_145 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.left.left.right.left.right.left) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_146 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.left.left.right.left.right.right) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_147 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.left.left.right.left.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_145⟩, statePart_146⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_148 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.left.left.right.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_144⟩, statePart_147⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_149 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.left.left.right.right.left.left) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_150 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.left.left.right.right.left.right) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_151 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.left.left.right.right.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_149⟩, statePart_150⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_152 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.left.left.right.right.right.left) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_153 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.left.left.right.right.right.right) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_154 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.left.left.right.right.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_152⟩, statePart_153⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_155 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.left.left.right.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_151⟩, statePart_154⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_156 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.left.left.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_148⟩, statePart_155⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_157 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.left.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_141⟩, statePart_156⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_158 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.left.right.left.left.left.left) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_159 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.left.right.left.left.left.right) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_160 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.left.right.left.left.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_158⟩, statePart_159⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_161 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.left.right.left.left.right.left) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_162 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.left.right.left.left.right.right) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_163 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.left.right.left.left.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_161⟩, statePart_162⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_164 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.left.right.left.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_160⟩, statePart_163⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_165 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.left.right.left.right.left.left) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_166 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.left.right.left.right.left.right) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_167 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.left.right.left.right.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_165⟩, statePart_166⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_168 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.left.right.left.right.right.left) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_169 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.left.right.left.right.right.right) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_170 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.left.right.left.right.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_168⟩, statePart_169⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_171 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.left.right.left.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_167⟩, statePart_170⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_172 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.left.right.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_164⟩, statePart_171⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_173 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.left.right.right.left.left.left) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_174 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.left.right.right.left.left.right) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_175 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.left.right.right.left.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_173⟩, statePart_174⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_176 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.left.right.right.left.right.left) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_177 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.left.right.right.left.right.right) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_178 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.left.right.right.left.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_176⟩, statePart_177⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_179 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.left.right.right.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_175⟩, statePart_178⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_180 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.left.right.right.right.left.left) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_181 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.left.right.right.right.left.right) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_182 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.left.right.right.right.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_180⟩, statePart_181⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_183 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.left.right.right.right.right.left) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_184 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.left.right.right.right.right.right) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_185 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.left.right.right.right.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_183⟩, statePart_184⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_186 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.left.right.right.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_182⟩, statePart_185⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_187 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.left.right.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_179⟩, statePart_186⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_188 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.left.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_172⟩, statePart_187⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_189 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_157⟩, statePart_188⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_190 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.right.left.left.left.left.left) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_191 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.right.left.left.left.left.right) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_192 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.right.left.left.left.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_190⟩, statePart_191⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_193 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.right.left.left.left.right.left) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_194 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.right.left.left.left.right.right) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_195 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.right.left.left.left.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_193⟩, statePart_194⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_196 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.right.left.left.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_192⟩, statePart_195⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_197 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.right.left.left.right.left.left) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_198 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.right.left.left.right.left.right) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_199 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.right.left.left.right.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_197⟩, statePart_198⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_200 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.right.left.left.right.right.left) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_201 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.right.left.left.right.right.right) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_202 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.right.left.left.right.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_200⟩, statePart_201⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_203 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.right.left.left.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_199⟩, statePart_202⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_204 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.right.left.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_196⟩, statePart_203⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_205 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.right.left.right.left.left.left) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_206 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.right.left.right.left.left.right) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_207 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.right.left.right.left.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_205⟩, statePart_206⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_208 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.right.left.right.left.right.left) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_209 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.right.left.right.left.right.right) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_210 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.right.left.right.left.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_208⟩, statePart_209⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_211 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.right.left.right.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_207⟩, statePart_210⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_212 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.right.left.right.right.left.left) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_213 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.right.left.right.right.left.right) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_214 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.right.left.right.right.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_212⟩, statePart_213⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_215 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.right.left.right.right.right.left) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_216 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.right.left.right.right.right.right) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_217 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.right.left.right.right.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_215⟩, statePart_216⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_218 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.right.left.right.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_214⟩, statePart_217⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_219 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.right.left.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_211⟩, statePart_218⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_220 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.right.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_204⟩, statePart_219⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_221 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.right.right.left.left.left.left) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_222 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.right.right.left.left.left.right) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_223 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.right.right.left.left.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_221⟩, statePart_222⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_224 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.right.right.left.left.right.left) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_225 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.right.right.left.left.right.right) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_226 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.right.right.left.left.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_224⟩, statePart_225⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_227 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.right.right.left.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_223⟩, statePart_226⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_228 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.right.right.left.right.left.left) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_229 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.right.right.left.right.left.right) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_230 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.right.right.left.right.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_228⟩, statePart_229⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_231 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.right.right.left.right.right.left) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_232 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.right.right.left.right.right.right) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_233 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.right.right.left.right.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_231⟩, statePart_232⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_234 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.right.right.left.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_230⟩, statePart_233⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_235 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.right.right.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_227⟩, statePart_234⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_236 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.right.right.right.left.left.left) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_237 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.right.right.right.left.left.right) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_238 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.right.right.right.left.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_236⟩, statePart_237⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_239 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.right.right.right.left.right.left) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_240 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.right.right.right.left.right.right) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_241 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.right.right.right.left.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_239⟩, statePart_240⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_242 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.right.right.right.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_238⟩, statePart_241⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_243 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.right.right.right.right.left.left) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_244 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.right.right.right.right.left.right) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_245 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.right.right.right.right.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_243⟩, statePart_244⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_246 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.right.right.right.right.right.left) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_247 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.right.right.right.right.right.right) = true := by
  decide +kernel

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_248 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.right.right.right.right.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_246⟩, statePart_247⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_249 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.right.right.right.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_245⟩, statePart_248⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_250 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.right.right.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_242⟩, statePart_249⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_251 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.right.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_235⟩, statePart_250⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_252 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_220⟩, statePart_251⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_253 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_189⟩, statePart_252⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
private theorem statePart_254 :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, statePart_126⟩, statePart_253⟩

set_option maxHeartbeats 0 in
-- This finite certificate is reduced by the Lean kernel.
/-- Corollary 19: kernel verification of quarter 1 of the
forty-symbol state table, including every outgoing branch. -/
theorem vertexQuarter0_checked :
    indexedAll checkVertexEntry (FortyData.vertexTable.left.left) = true :=
  statePart_254

end Queens.Finite.Forty
