import Queens.Finite.ReachabilityCore
import Mathlib.Tactic.FinCases

/-!
# Bounded kernel checks for the local invariant

Generated by `scripts/export_kernel_checks.py`; do not edit by hand.
Each proof independently recomputes at most 64 states of Proposition 17.
The checker propagates every failure and validates every successor.
Separating the checks bounds the Lean kernel's reduction cache.
-/

namespace Queens.Finite

set_option Elab.async false
set_option maxRecDepth 100000

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_0 :
    (Data.stateChunks[0]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_1 :
    (Data.stateChunks[1]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_2 :
    (Data.stateChunks[2]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_3 :
    (Data.stateChunks[3]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_4 :
    (Data.stateChunks[4]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_5 :
    (Data.stateChunks[5]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_6 :
    (Data.stateChunks[6]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_7 :
    (Data.stateChunks[7]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_8 :
    (Data.stateChunks[8]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_9 :
    (Data.stateChunks[9]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_10 :
    (Data.stateChunks[10]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_11 :
    (Data.stateChunks[11]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_12 :
    (Data.stateChunks[12]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_13 :
    (Data.stateChunks[13]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_14 :
    (Data.stateChunks[14]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_15 :
    (Data.stateChunks[15]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_16 :
    (Data.stateChunks[16]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_17 :
    (Data.stateChunks[17]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_18 :
    (Data.stateChunks[18]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_19 :
    (Data.stateChunks[19]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_20 :
    (Data.stateChunks[20]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_21 :
    (Data.stateChunks[21]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_22 :
    (Data.stateChunks[22]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_23 :
    (Data.stateChunks[23]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_24 :
    (Data.stateChunks[24]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_25 :
    (Data.stateChunks[25]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_26 :
    (Data.stateChunks[26]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_27 :
    (Data.stateChunks[27]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_28 :
    (Data.stateChunks[28]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_29 :
    (Data.stateChunks[29]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_30 :
    (Data.stateChunks[30]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_31 :
    (Data.stateChunks[31]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_32 :
    (Data.stateChunks[32]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_33 :
    (Data.stateChunks[33]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_34 :
    (Data.stateChunks[34]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_35 :
    (Data.stateChunks[35]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_36 :
    (Data.stateChunks[36]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_37 :
    (Data.stateChunks[37]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_38 :
    (Data.stateChunks[38]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_39 :
    (Data.stateChunks[39]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_40 :
    (Data.stateChunks[40]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_41 :
    (Data.stateChunks[41]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_42 :
    (Data.stateChunks[42]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_43 :
    (Data.stateChunks[43]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_44 :
    (Data.stateChunks[44]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_45 :
    (Data.stateChunks[45]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_46 :
    (Data.stateChunks[46]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_47 :
    (Data.stateChunks[47]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_48 :
    (Data.stateChunks[48]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_49 :
    (Data.stateChunks[49]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_50 :
    (Data.stateChunks[50]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_51 :
    (Data.stateChunks[51]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_52 :
    (Data.stateChunks[52]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_53 :
    (Data.stateChunks[53]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_54 :
    (Data.stateChunks[54]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_55 :
    (Data.stateChunks[55]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_56 :
    (Data.stateChunks[56]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_57 :
    (Data.stateChunks[57]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_58 :
    (Data.stateChunks[58]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_59 :
    (Data.stateChunks[59]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_60 :
    (Data.stateChunks[60]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_61 :
    (Data.stateChunks[61]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_62 :
    (Data.stateChunks[62]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_63 :
    (Data.stateChunks[63]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_64 :
    (Data.stateChunks[64]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_65 :
    (Data.stateChunks[65]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_66 :
    (Data.stateChunks[66]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_67 :
    (Data.stateChunks[67]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_68 :
    (Data.stateChunks[68]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_69 :
    (Data.stateChunks[69]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_70 :
    (Data.stateChunks[70]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_71 :
    (Data.stateChunks[71]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_72 :
    (Data.stateChunks[72]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_73 :
    (Data.stateChunks[73]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_74 :
    (Data.stateChunks[74]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_75 :
    (Data.stateChunks[75]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_76 :
    (Data.stateChunks[76]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_77 :
    (Data.stateChunks[77]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_78 :
    (Data.stateChunks[78]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_79 :
    (Data.stateChunks[79]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_80 :
    (Data.stateChunks[80]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_81 :
    (Data.stateChunks[81]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_82 :
    (Data.stateChunks[82]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_83 :
    (Data.stateChunks[83]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_84 :
    (Data.stateChunks[84]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_85 :
    (Data.stateChunks[85]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_86 :
    (Data.stateChunks[86]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_87 :
    (Data.stateChunks[87]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_88 :
    (Data.stateChunks[88]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_89 :
    (Data.stateChunks[89]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_90 :
    (Data.stateChunks[90]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_91 :
    (Data.stateChunks[91]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_92 :
    (Data.stateChunks[92]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_93 :
    (Data.stateChunks[93]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_94 :
    (Data.stateChunks[94]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_95 :
    (Data.stateChunks[95]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_96 :
    (Data.stateChunks[96]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_97 :
    (Data.stateChunks[97]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_98 :
    (Data.stateChunks[98]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_99 :
    (Data.stateChunks[99]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_100 :
    (Data.stateChunks[100]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_101 :
    (Data.stateChunks[101]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_102 :
    (Data.stateChunks[102]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_103 :
    (Data.stateChunks[103]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_104 :
    (Data.stateChunks[104]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_105 :
    (Data.stateChunks[105]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_106 :
    (Data.stateChunks[106]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_107 :
    (Data.stateChunks[107]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_108 :
    (Data.stateChunks[108]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedChunk_109 :
    (Data.stateChunks[109]!).all checkParentState = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem all_chunks_checked :
    ∀ i : Fin 110, (Data.stateChunks[i.val]!).all checkParentState = true := by
  intro i
  fin_cases i
  · exact checkedChunk_0
  · exact checkedChunk_1
  · exact checkedChunk_2
  · exact checkedChunk_3
  · exact checkedChunk_4
  · exact checkedChunk_5
  · exact checkedChunk_6
  · exact checkedChunk_7
  · exact checkedChunk_8
  · exact checkedChunk_9
  · exact checkedChunk_10
  · exact checkedChunk_11
  · exact checkedChunk_12
  · exact checkedChunk_13
  · exact checkedChunk_14
  · exact checkedChunk_15
  · exact checkedChunk_16
  · exact checkedChunk_17
  · exact checkedChunk_18
  · exact checkedChunk_19
  · exact checkedChunk_20
  · exact checkedChunk_21
  · exact checkedChunk_22
  · exact checkedChunk_23
  · exact checkedChunk_24
  · exact checkedChunk_25
  · exact checkedChunk_26
  · exact checkedChunk_27
  · exact checkedChunk_28
  · exact checkedChunk_29
  · exact checkedChunk_30
  · exact checkedChunk_31
  · exact checkedChunk_32
  · exact checkedChunk_33
  · exact checkedChunk_34
  · exact checkedChunk_35
  · exact checkedChunk_36
  · exact checkedChunk_37
  · exact checkedChunk_38
  · exact checkedChunk_39
  · exact checkedChunk_40
  · exact checkedChunk_41
  · exact checkedChunk_42
  · exact checkedChunk_43
  · exact checkedChunk_44
  · exact checkedChunk_45
  · exact checkedChunk_46
  · exact checkedChunk_47
  · exact checkedChunk_48
  · exact checkedChunk_49
  · exact checkedChunk_50
  · exact checkedChunk_51
  · exact checkedChunk_52
  · exact checkedChunk_53
  · exact checkedChunk_54
  · exact checkedChunk_55
  · exact checkedChunk_56
  · exact checkedChunk_57
  · exact checkedChunk_58
  · exact checkedChunk_59
  · exact checkedChunk_60
  · exact checkedChunk_61
  · exact checkedChunk_62
  · exact checkedChunk_63
  · exact checkedChunk_64
  · exact checkedChunk_65
  · exact checkedChunk_66
  · exact checkedChunk_67
  · exact checkedChunk_68
  · exact checkedChunk_69
  · exact checkedChunk_70
  · exact checkedChunk_71
  · exact checkedChunk_72
  · exact checkedChunk_73
  · exact checkedChunk_74
  · exact checkedChunk_75
  · exact checkedChunk_76
  · exact checkedChunk_77
  · exact checkedChunk_78
  · exact checkedChunk_79
  · exact checkedChunk_80
  · exact checkedChunk_81
  · exact checkedChunk_82
  · exact checkedChunk_83
  · exact checkedChunk_84
  · exact checkedChunk_85
  · exact checkedChunk_86
  · exact checkedChunk_87
  · exact checkedChunk_88
  · exact checkedChunk_89
  · exact checkedChunk_90
  · exact checkedChunk_91
  · exact checkedChunk_92
  · exact checkedChunk_93
  · exact checkedChunk_94
  · exact checkedChunk_95
  · exact checkedChunk_96
  · exact checkedChunk_97
  · exact checkedChunk_98
  · exact checkedChunk_99
  · exact checkedChunk_100
  · exact checkedChunk_101
  · exact checkedChunk_102
  · exact checkedChunk_103
  · exact checkedChunk_104
  · exact checkedChunk_105
  · exact checkedChunk_106
  · exact checkedChunk_107
  · exact checkedChunk_108
  · exact checkedChunk_109

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
/-- Proposition 17: every state in the candidate invariant satisfies the
independently recomputed check. Each bounded check is verified by Lean's
kernel; the final assembly covers every state in the original table. -/
theorem predecessor_states_checked : Data.states.all checkParentState = true := by
  apply all_flatten_of_all_chunks
  intro i
  have hi : i.val < 110 := i.isLt
  simpa only [getElem!_pos Data.stateChunks i.val i.isLt] using all_chunks_checked ⟨i.val, hi⟩

end Queens.Finite
