import Queens.Finite.StateCountCore
import Mathlib.Tactic.FinCases

/-!
# Bounded kernel checks of the edge count

Generated by `scripts/export_kernel_checks.py`; do not edit by hand.
Python supplies candidate partial sums; every sum is recomputed by the
Lean kernel from Algorithm 1, with duplicate successors removed.
-/

-- Generated tree literals and check statements preserve the evaluation layout.
set_option linter.style.longLine false

namespace Queens.Finite

set_option Elab.async false
set_option maxRecDepth 100000

private def expectedChunkCounts (i : Fin 110) : ℕ :=
  #[64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 77, 131, 142, 104, 98, 92, 89, 94, 69, 65, 66, 70, 69, 69, 67, 65, 72, 69, 75, 69, 72, 92, 106, 107, 83, 74, 75, 67, 64, 64, 82, 111, 98, 153, 83, 77, 101, 89, 92, 111, 77, 86, 99, 87, 99, 90, 101, 85, 87, 75, 82, 94, 64, 81, 73, 67, 72, 72, 71, 75, 100, 91, 64, 38][i.val]!

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_0 :
    ((Data.stateChunks[0]!).map stateSuccessorCount).sum = 64 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_1 :
    ((Data.stateChunks[1]!).map stateSuccessorCount).sum = 64 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_2 :
    ((Data.stateChunks[2]!).map stateSuccessorCount).sum = 64 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_3 :
    ((Data.stateChunks[3]!).map stateSuccessorCount).sum = 64 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_4 :
    ((Data.stateChunks[4]!).map stateSuccessorCount).sum = 64 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_5 :
    ((Data.stateChunks[5]!).map stateSuccessorCount).sum = 64 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_6 :
    ((Data.stateChunks[6]!).map stateSuccessorCount).sum = 64 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_7 :
    ((Data.stateChunks[7]!).map stateSuccessorCount).sum = 64 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_8 :
    ((Data.stateChunks[8]!).map stateSuccessorCount).sum = 64 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_9 :
    ((Data.stateChunks[9]!).map stateSuccessorCount).sum = 64 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_10 :
    ((Data.stateChunks[10]!).map stateSuccessorCount).sum = 64 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_11 :
    ((Data.stateChunks[11]!).map stateSuccessorCount).sum = 64 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_12 :
    ((Data.stateChunks[12]!).map stateSuccessorCount).sum = 64 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_13 :
    ((Data.stateChunks[13]!).map stateSuccessorCount).sum = 64 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_14 :
    ((Data.stateChunks[14]!).map stateSuccessorCount).sum = 64 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_15 :
    ((Data.stateChunks[15]!).map stateSuccessorCount).sum = 64 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_16 :
    ((Data.stateChunks[16]!).map stateSuccessorCount).sum = 64 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_17 :
    ((Data.stateChunks[17]!).map stateSuccessorCount).sum = 64 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_18 :
    ((Data.stateChunks[18]!).map stateSuccessorCount).sum = 64 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_19 :
    ((Data.stateChunks[19]!).map stateSuccessorCount).sum = 64 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_20 :
    ((Data.stateChunks[20]!).map stateSuccessorCount).sum = 64 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_21 :
    ((Data.stateChunks[21]!).map stateSuccessorCount).sum = 64 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_22 :
    ((Data.stateChunks[22]!).map stateSuccessorCount).sum = 64 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_23 :
    ((Data.stateChunks[23]!).map stateSuccessorCount).sum = 64 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_24 :
    ((Data.stateChunks[24]!).map stateSuccessorCount).sum = 64 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_25 :
    ((Data.stateChunks[25]!).map stateSuccessorCount).sum = 64 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_26 :
    ((Data.stateChunks[26]!).map stateSuccessorCount).sum = 64 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_27 :
    ((Data.stateChunks[27]!).map stateSuccessorCount).sum = 64 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_28 :
    ((Data.stateChunks[28]!).map stateSuccessorCount).sum = 64 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_29 :
    ((Data.stateChunks[29]!).map stateSuccessorCount).sum = 64 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_30 :
    ((Data.stateChunks[30]!).map stateSuccessorCount).sum = 64 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_31 :
    ((Data.stateChunks[31]!).map stateSuccessorCount).sum = 64 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_32 :
    ((Data.stateChunks[32]!).map stateSuccessorCount).sum = 64 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_33 :
    ((Data.stateChunks[33]!).map stateSuccessorCount).sum = 64 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_34 :
    ((Data.stateChunks[34]!).map stateSuccessorCount).sum = 64 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_35 :
    ((Data.stateChunks[35]!).map stateSuccessorCount).sum = 64 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_36 :
    ((Data.stateChunks[36]!).map stateSuccessorCount).sum = 64 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_37 :
    ((Data.stateChunks[37]!).map stateSuccessorCount).sum = 64 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_38 :
    ((Data.stateChunks[38]!).map stateSuccessorCount).sum = 64 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_39 :
    ((Data.stateChunks[39]!).map stateSuccessorCount).sum = 64 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_40 :
    ((Data.stateChunks[40]!).map stateSuccessorCount).sum = 64 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_41 :
    ((Data.stateChunks[41]!).map stateSuccessorCount).sum = 64 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_42 :
    ((Data.stateChunks[42]!).map stateSuccessorCount).sum = 64 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_43 :
    ((Data.stateChunks[43]!).map stateSuccessorCount).sum = 64 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_44 :
    ((Data.stateChunks[44]!).map stateSuccessorCount).sum = 64 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_45 :
    ((Data.stateChunks[45]!).map stateSuccessorCount).sum = 64 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_46 :
    ((Data.stateChunks[46]!).map stateSuccessorCount).sum = 77 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_47 :
    ((Data.stateChunks[47]!).map stateSuccessorCount).sum = 131 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_48 :
    ((Data.stateChunks[48]!).map stateSuccessorCount).sum = 142 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_49 :
    ((Data.stateChunks[49]!).map stateSuccessorCount).sum = 104 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_50 :
    ((Data.stateChunks[50]!).map stateSuccessorCount).sum = 98 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_51 :
    ((Data.stateChunks[51]!).map stateSuccessorCount).sum = 92 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_52 :
    ((Data.stateChunks[52]!).map stateSuccessorCount).sum = 89 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_53 :
    ((Data.stateChunks[53]!).map stateSuccessorCount).sum = 94 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_54 :
    ((Data.stateChunks[54]!).map stateSuccessorCount).sum = 69 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_55 :
    ((Data.stateChunks[55]!).map stateSuccessorCount).sum = 65 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_56 :
    ((Data.stateChunks[56]!).map stateSuccessorCount).sum = 66 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_57 :
    ((Data.stateChunks[57]!).map stateSuccessorCount).sum = 70 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_58 :
    ((Data.stateChunks[58]!).map stateSuccessorCount).sum = 69 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_59 :
    ((Data.stateChunks[59]!).map stateSuccessorCount).sum = 69 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_60 :
    ((Data.stateChunks[60]!).map stateSuccessorCount).sum = 67 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_61 :
    ((Data.stateChunks[61]!).map stateSuccessorCount).sum = 65 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_62 :
    ((Data.stateChunks[62]!).map stateSuccessorCount).sum = 72 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_63 :
    ((Data.stateChunks[63]!).map stateSuccessorCount).sum = 69 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_64 :
    ((Data.stateChunks[64]!).map stateSuccessorCount).sum = 75 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_65 :
    ((Data.stateChunks[65]!).map stateSuccessorCount).sum = 69 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_66 :
    ((Data.stateChunks[66]!).map stateSuccessorCount).sum = 72 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_67 :
    ((Data.stateChunks[67]!).map stateSuccessorCount).sum = 92 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_68 :
    ((Data.stateChunks[68]!).map stateSuccessorCount).sum = 106 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_69 :
    ((Data.stateChunks[69]!).map stateSuccessorCount).sum = 107 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_70 :
    ((Data.stateChunks[70]!).map stateSuccessorCount).sum = 83 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_71 :
    ((Data.stateChunks[71]!).map stateSuccessorCount).sum = 74 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_72 :
    ((Data.stateChunks[72]!).map stateSuccessorCount).sum = 75 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_73 :
    ((Data.stateChunks[73]!).map stateSuccessorCount).sum = 67 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_74 :
    ((Data.stateChunks[74]!).map stateSuccessorCount).sum = 64 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_75 :
    ((Data.stateChunks[75]!).map stateSuccessorCount).sum = 64 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_76 :
    ((Data.stateChunks[76]!).map stateSuccessorCount).sum = 82 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_77 :
    ((Data.stateChunks[77]!).map stateSuccessorCount).sum = 111 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_78 :
    ((Data.stateChunks[78]!).map stateSuccessorCount).sum = 98 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_79 :
    ((Data.stateChunks[79]!).map stateSuccessorCount).sum = 153 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_80 :
    ((Data.stateChunks[80]!).map stateSuccessorCount).sum = 83 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_81 :
    ((Data.stateChunks[81]!).map stateSuccessorCount).sum = 77 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_82 :
    ((Data.stateChunks[82]!).map stateSuccessorCount).sum = 101 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_83 :
    ((Data.stateChunks[83]!).map stateSuccessorCount).sum = 89 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_84 :
    ((Data.stateChunks[84]!).map stateSuccessorCount).sum = 92 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_85 :
    ((Data.stateChunks[85]!).map stateSuccessorCount).sum = 111 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_86 :
    ((Data.stateChunks[86]!).map stateSuccessorCount).sum = 77 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_87 :
    ((Data.stateChunks[87]!).map stateSuccessorCount).sum = 86 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_88 :
    ((Data.stateChunks[88]!).map stateSuccessorCount).sum = 99 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_89 :
    ((Data.stateChunks[89]!).map stateSuccessorCount).sum = 87 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_90 :
    ((Data.stateChunks[90]!).map stateSuccessorCount).sum = 99 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_91 :
    ((Data.stateChunks[91]!).map stateSuccessorCount).sum = 90 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_92 :
    ((Data.stateChunks[92]!).map stateSuccessorCount).sum = 101 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_93 :
    ((Data.stateChunks[93]!).map stateSuccessorCount).sum = 85 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_94 :
    ((Data.stateChunks[94]!).map stateSuccessorCount).sum = 87 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_95 :
    ((Data.stateChunks[95]!).map stateSuccessorCount).sum = 75 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_96 :
    ((Data.stateChunks[96]!).map stateSuccessorCount).sum = 82 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_97 :
    ((Data.stateChunks[97]!).map stateSuccessorCount).sum = 94 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_98 :
    ((Data.stateChunks[98]!).map stateSuccessorCount).sum = 64 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_99 :
    ((Data.stateChunks[99]!).map stateSuccessorCount).sum = 81 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_100 :
    ((Data.stateChunks[100]!).map stateSuccessorCount).sum = 73 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_101 :
    ((Data.stateChunks[101]!).map stateSuccessorCount).sum = 67 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_102 :
    ((Data.stateChunks[102]!).map stateSuccessorCount).sum = 72 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_103 :
    ((Data.stateChunks[103]!).map stateSuccessorCount).sum = 72 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_104 :
    ((Data.stateChunks[104]!).map stateSuccessorCount).sum = 71 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_105 :
    ((Data.stateChunks[105]!).map stateSuccessorCount).sum = 75 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_106 :
    ((Data.stateChunks[106]!).map stateSuccessorCount).sum = 100 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_107 :
    ((Data.stateChunks[107]!).map stateSuccessorCount).sum = 91 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_108 :
    ((Data.stateChunks[108]!).map stateSuccessorCount).sum = 64 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem countChunk_109 :
    ((Data.stateChunks[109]!).map stateSuccessorCount).sum = 38 := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem all_chunk_counts :
    ∀ i : Fin 110, ((Data.stateChunks[i.val]!).map stateSuccessorCount).sum =
      expectedChunkCounts i := by
  intro i
  fin_cases i
  · exact countChunk_0
  · exact countChunk_1
  · exact countChunk_2
  · exact countChunk_3
  · exact countChunk_4
  · exact countChunk_5
  · exact countChunk_6
  · exact countChunk_7
  · exact countChunk_8
  · exact countChunk_9
  · exact countChunk_10
  · exact countChunk_11
  · exact countChunk_12
  · exact countChunk_13
  · exact countChunk_14
  · exact countChunk_15
  · exact countChunk_16
  · exact countChunk_17
  · exact countChunk_18
  · exact countChunk_19
  · exact countChunk_20
  · exact countChunk_21
  · exact countChunk_22
  · exact countChunk_23
  · exact countChunk_24
  · exact countChunk_25
  · exact countChunk_26
  · exact countChunk_27
  · exact countChunk_28
  · exact countChunk_29
  · exact countChunk_30
  · exact countChunk_31
  · exact countChunk_32
  · exact countChunk_33
  · exact countChunk_34
  · exact countChunk_35
  · exact countChunk_36
  · exact countChunk_37
  · exact countChunk_38
  · exact countChunk_39
  · exact countChunk_40
  · exact countChunk_41
  · exact countChunk_42
  · exact countChunk_43
  · exact countChunk_44
  · exact countChunk_45
  · exact countChunk_46
  · exact countChunk_47
  · exact countChunk_48
  · exact countChunk_49
  · exact countChunk_50
  · exact countChunk_51
  · exact countChunk_52
  · exact countChunk_53
  · exact countChunk_54
  · exact countChunk_55
  · exact countChunk_56
  · exact countChunk_57
  · exact countChunk_58
  · exact countChunk_59
  · exact countChunk_60
  · exact countChunk_61
  · exact countChunk_62
  · exact countChunk_63
  · exact countChunk_64
  · exact countChunk_65
  · exact countChunk_66
  · exact countChunk_67
  · exact countChunk_68
  · exact countChunk_69
  · exact countChunk_70
  · exact countChunk_71
  · exact countChunk_72
  · exact countChunk_73
  · exact countChunk_74
  · exact countChunk_75
  · exact countChunk_76
  · exact countChunk_77
  · exact countChunk_78
  · exact countChunk_79
  · exact countChunk_80
  · exact countChunk_81
  · exact countChunk_82
  · exact countChunk_83
  · exact countChunk_84
  · exact countChunk_85
  · exact countChunk_86
  · exact countChunk_87
  · exact countChunk_88
  · exact countChunk_89
  · exact countChunk_90
  · exact countChunk_91
  · exact countChunk_92
  · exact countChunk_93
  · exact countChunk_94
  · exact countChunk_95
  · exact countChunk_96
  · exact countChunk_97
  · exact countChunk_98
  · exact countChunk_99
  · exact countChunk_100
  · exact countChunk_101
  · exact countChunk_102
  · exact countChunk_103
  · exact countChunk_104
  · exact countChunk_105
  · exact countChunk_106
  · exact countChunk_107
  · exact countChunk_108
  · exact countChunk_109

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
/-- Proposition 17: recomputing all distinct-successor sets gives 8327 edges.
Each partial count is independently verified by the Lean kernel. -/
theorem state_edge_count : stateEdgeCount = 8327 := by
  change (Data.stateChunks.toList.flatten.map stateSuccessorCount).sum = 8327
  rw [sum_flatten_eq_sum_ofFn]
  have hcounts : (fun i : Fin Data.stateChunks.size =>
      (Data.stateChunks[i.val].map stateSuccessorCount).sum) = expectedChunkCounts := by
    funext i
    simpa only [getElem!_pos Data.stateChunks i.val i.isLt] using all_chunk_counts i
  rw [hcounts]
  decide +kernel

end Queens.Finite
