import Queens.Finite.WindowChecks

/-!
# Bounded kernel checks of the window bounds at the vertices

Generated by `python3 scripts/export_window_bounds.py`; do not edit by hand.
Each proof checks at most 64 entries of the window-bound tree or of
the history-graph tree. Separating the checks bounds the Lean
kernel's reduction cache; no entry is omitted.
-/

-- Generated tree literals and check statements preserve the evaluation layout.
set_option linter.style.longLine false

namespace Queens.Finite

set_option Elab.async false
set_option maxRecDepth 100000

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_0 :
    indexedAll checkWindowVertex (Data.windowBounds.left.left.left.left.left.left) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_1 :
    indexedAll checkWindowVertex (Data.windowBounds.left.left.left.left.left.right) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_2 :
    indexedAll checkWindowVertex (Data.windowBounds.left.left.left.left.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedWindowVertices_0⟩, checkedWindowVertices_1⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_3 :
    indexedAll checkWindowVertex (Data.windowBounds.left.left.left.left.right) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_4 :
    indexedAll checkWindowVertex (Data.windowBounds.left.left.left.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedWindowVertices_2⟩, checkedWindowVertices_3⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_5 :
    indexedAll checkWindowVertex (Data.windowBounds.left.left.left.right.left.left) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_6 :
    indexedAll checkWindowVertex (Data.windowBounds.left.left.left.right.left.right) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_7 :
    indexedAll checkWindowVertex (Data.windowBounds.left.left.left.right.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedWindowVertices_5⟩, checkedWindowVertices_6⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_8 :
    indexedAll checkWindowVertex (Data.windowBounds.left.left.left.right.right) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_9 :
    indexedAll checkWindowVertex (Data.windowBounds.left.left.left.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedWindowVertices_7⟩, checkedWindowVertices_8⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_10 :
    indexedAll checkWindowVertex (Data.windowBounds.left.left.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedWindowVertices_4⟩, checkedWindowVertices_9⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_11 :
    indexedAll checkWindowVertex (Data.windowBounds.left.left.right.left.left.left) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_12 :
    indexedAll checkWindowVertex (Data.windowBounds.left.left.right.left.left.right) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_13 :
    indexedAll checkWindowVertex (Data.windowBounds.left.left.right.left.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedWindowVertices_11⟩, checkedWindowVertices_12⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_14 :
    indexedAll checkWindowVertex (Data.windowBounds.left.left.right.left.right) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_15 :
    indexedAll checkWindowVertex (Data.windowBounds.left.left.right.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedWindowVertices_13⟩, checkedWindowVertices_14⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_16 :
    indexedAll checkWindowVertex (Data.windowBounds.left.left.right.right.left.left) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_17 :
    indexedAll checkWindowVertex (Data.windowBounds.left.left.right.right.left.right) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_18 :
    indexedAll checkWindowVertex (Data.windowBounds.left.left.right.right.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedWindowVertices_16⟩, checkedWindowVertices_17⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_19 :
    indexedAll checkWindowVertex (Data.windowBounds.left.left.right.right.right) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_20 :
    indexedAll checkWindowVertex (Data.windowBounds.left.left.right.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedWindowVertices_18⟩, checkedWindowVertices_19⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_21 :
    indexedAll checkWindowVertex (Data.windowBounds.left.left.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedWindowVertices_15⟩, checkedWindowVertices_20⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_22 :
    indexedAll checkWindowVertex (Data.windowBounds.left.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedWindowVertices_10⟩, checkedWindowVertices_21⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_23 :
    indexedAll checkWindowVertex (Data.windowBounds.left.right.left.left.left.left) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_24 :
    indexedAll checkWindowVertex (Data.windowBounds.left.right.left.left.left.right) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_25 :
    indexedAll checkWindowVertex (Data.windowBounds.left.right.left.left.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedWindowVertices_23⟩, checkedWindowVertices_24⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_26 :
    indexedAll checkWindowVertex (Data.windowBounds.left.right.left.left.right) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_27 :
    indexedAll checkWindowVertex (Data.windowBounds.left.right.left.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedWindowVertices_25⟩, checkedWindowVertices_26⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_28 :
    indexedAll checkWindowVertex (Data.windowBounds.left.right.left.right.left.left) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_29 :
    indexedAll checkWindowVertex (Data.windowBounds.left.right.left.right.left.right) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_30 :
    indexedAll checkWindowVertex (Data.windowBounds.left.right.left.right.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedWindowVertices_28⟩, checkedWindowVertices_29⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_31 :
    indexedAll checkWindowVertex (Data.windowBounds.left.right.left.right.right) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_32 :
    indexedAll checkWindowVertex (Data.windowBounds.left.right.left.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedWindowVertices_30⟩, checkedWindowVertices_31⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_33 :
    indexedAll checkWindowVertex (Data.windowBounds.left.right.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedWindowVertices_27⟩, checkedWindowVertices_32⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_34 :
    indexedAll checkWindowVertex (Data.windowBounds.left.right.right.left.left.left) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_35 :
    indexedAll checkWindowVertex (Data.windowBounds.left.right.right.left.left.right) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_36 :
    indexedAll checkWindowVertex (Data.windowBounds.left.right.right.left.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedWindowVertices_34⟩, checkedWindowVertices_35⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_37 :
    indexedAll checkWindowVertex (Data.windowBounds.left.right.right.left.right) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_38 :
    indexedAll checkWindowVertex (Data.windowBounds.left.right.right.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedWindowVertices_36⟩, checkedWindowVertices_37⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_39 :
    indexedAll checkWindowVertex (Data.windowBounds.left.right.right.right.left) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_40 :
    indexedAll checkWindowVertex (Data.windowBounds.left.right.right.right.right) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_41 :
    indexedAll checkWindowVertex (Data.windowBounds.left.right.right.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedWindowVertices_39⟩, checkedWindowVertices_40⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_42 :
    indexedAll checkWindowVertex (Data.windowBounds.left.right.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedWindowVertices_38⟩, checkedWindowVertices_41⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_43 :
    indexedAll checkWindowVertex (Data.windowBounds.left.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedWindowVertices_33⟩, checkedWindowVertices_42⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_44 :
    indexedAll checkWindowVertex (Data.windowBounds.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedWindowVertices_22⟩, checkedWindowVertices_43⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_45 :
    indexedAll checkWindowVertex (Data.windowBounds.right.left.left.left.left.left) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_46 :
    indexedAll checkWindowVertex (Data.windowBounds.right.left.left.left.left.right) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_47 :
    indexedAll checkWindowVertex (Data.windowBounds.right.left.left.left.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedWindowVertices_45⟩, checkedWindowVertices_46⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_48 :
    indexedAll checkWindowVertex (Data.windowBounds.right.left.left.left.right) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_49 :
    indexedAll checkWindowVertex (Data.windowBounds.right.left.left.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedWindowVertices_47⟩, checkedWindowVertices_48⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_50 :
    indexedAll checkWindowVertex (Data.windowBounds.right.left.left.right.left.left) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_51 :
    indexedAll checkWindowVertex (Data.windowBounds.right.left.left.right.left.right) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_52 :
    indexedAll checkWindowVertex (Data.windowBounds.right.left.left.right.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedWindowVertices_50⟩, checkedWindowVertices_51⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_53 :
    indexedAll checkWindowVertex (Data.windowBounds.right.left.left.right.right) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_54 :
    indexedAll checkWindowVertex (Data.windowBounds.right.left.left.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedWindowVertices_52⟩, checkedWindowVertices_53⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_55 :
    indexedAll checkWindowVertex (Data.windowBounds.right.left.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedWindowVertices_49⟩, checkedWindowVertices_54⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_56 :
    indexedAll checkWindowVertex (Data.windowBounds.right.left.right.left.left.left) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_57 :
    indexedAll checkWindowVertex (Data.windowBounds.right.left.right.left.left.right) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_58 :
    indexedAll checkWindowVertex (Data.windowBounds.right.left.right.left.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedWindowVertices_56⟩, checkedWindowVertices_57⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_59 :
    indexedAll checkWindowVertex (Data.windowBounds.right.left.right.left.right) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_60 :
    indexedAll checkWindowVertex (Data.windowBounds.right.left.right.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedWindowVertices_58⟩, checkedWindowVertices_59⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_61 :
    indexedAll checkWindowVertex (Data.windowBounds.right.left.right.right.left) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_62 :
    indexedAll checkWindowVertex (Data.windowBounds.right.left.right.right.right) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_63 :
    indexedAll checkWindowVertex (Data.windowBounds.right.left.right.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedWindowVertices_61⟩, checkedWindowVertices_62⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_64 :
    indexedAll checkWindowVertex (Data.windowBounds.right.left.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedWindowVertices_60⟩, checkedWindowVertices_63⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_65 :
    indexedAll checkWindowVertex (Data.windowBounds.right.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedWindowVertices_55⟩, checkedWindowVertices_64⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_66 :
    indexedAll checkWindowVertex (Data.windowBounds.right.right.left.left.left.left) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_67 :
    indexedAll checkWindowVertex (Data.windowBounds.right.right.left.left.left.right) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_68 :
    indexedAll checkWindowVertex (Data.windowBounds.right.right.left.left.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedWindowVertices_66⟩, checkedWindowVertices_67⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_69 :
    indexedAll checkWindowVertex (Data.windowBounds.right.right.left.left.right) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_70 :
    indexedAll checkWindowVertex (Data.windowBounds.right.right.left.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedWindowVertices_68⟩, checkedWindowVertices_69⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_71 :
    indexedAll checkWindowVertex (Data.windowBounds.right.right.left.right.left.left) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_72 :
    indexedAll checkWindowVertex (Data.windowBounds.right.right.left.right.left.right) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_73 :
    indexedAll checkWindowVertex (Data.windowBounds.right.right.left.right.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedWindowVertices_71⟩, checkedWindowVertices_72⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_74 :
    indexedAll checkWindowVertex (Data.windowBounds.right.right.left.right.right) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_75 :
    indexedAll checkWindowVertex (Data.windowBounds.right.right.left.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedWindowVertices_73⟩, checkedWindowVertices_74⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_76 :
    indexedAll checkWindowVertex (Data.windowBounds.right.right.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedWindowVertices_70⟩, checkedWindowVertices_75⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_77 :
    indexedAll checkWindowVertex (Data.windowBounds.right.right.right.left.left.left) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_78 :
    indexedAll checkWindowVertex (Data.windowBounds.right.right.right.left.left.right) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_79 :
    indexedAll checkWindowVertex (Data.windowBounds.right.right.right.left.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedWindowVertices_77⟩, checkedWindowVertices_78⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_80 :
    indexedAll checkWindowVertex (Data.windowBounds.right.right.right.left.right) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_81 :
    indexedAll checkWindowVertex (Data.windowBounds.right.right.right.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedWindowVertices_79⟩, checkedWindowVertices_80⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_82 :
    indexedAll checkWindowVertex (Data.windowBounds.right.right.right.right.left) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_83 :
    indexedAll checkWindowVertex (Data.windowBounds.right.right.right.right.right) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_84 :
    indexedAll checkWindowVertex (Data.windowBounds.right.right.right.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedWindowVertices_82⟩, checkedWindowVertices_83⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_85 :
    indexedAll checkWindowVertex (Data.windowBounds.right.right.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedWindowVertices_81⟩, checkedWindowVertices_84⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_86 :
    indexedAll checkWindowVertex (Data.windowBounds.right.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedWindowVertices_76⟩, checkedWindowVertices_85⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_87 :
    indexedAll checkWindowVertex (Data.windowBounds.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedWindowVertices_65⟩, checkedWindowVertices_86⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedWindowVertices_88 :
    indexedAll checkWindowVertex (Data.windowBounds) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedWindowVertices_44⟩, checkedWindowVertices_87⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_0 :
    indexedAll hasWindowBound (Data.historyGraph.tree.left.left.left.left.left.left) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_1 :
    indexedAll hasWindowBound (Data.historyGraph.tree.left.left.left.left.left.right) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_2 :
    indexedAll hasWindowBound (Data.historyGraph.tree.left.left.left.left.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedGraphVertices_0⟩, checkedGraphVertices_1⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_3 :
    indexedAll hasWindowBound (Data.historyGraph.tree.left.left.left.left.right) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_4 :
    indexedAll hasWindowBound (Data.historyGraph.tree.left.left.left.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedGraphVertices_2⟩, checkedGraphVertices_3⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_5 :
    indexedAll hasWindowBound (Data.historyGraph.tree.left.left.left.right.left.left) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_6 :
    indexedAll hasWindowBound (Data.historyGraph.tree.left.left.left.right.left.right) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_7 :
    indexedAll hasWindowBound (Data.historyGraph.tree.left.left.left.right.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedGraphVertices_5⟩, checkedGraphVertices_6⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_8 :
    indexedAll hasWindowBound (Data.historyGraph.tree.left.left.left.right.right) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_9 :
    indexedAll hasWindowBound (Data.historyGraph.tree.left.left.left.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedGraphVertices_7⟩, checkedGraphVertices_8⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_10 :
    indexedAll hasWindowBound (Data.historyGraph.tree.left.left.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedGraphVertices_4⟩, checkedGraphVertices_9⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_11 :
    indexedAll hasWindowBound (Data.historyGraph.tree.left.left.right.left.left.left) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_12 :
    indexedAll hasWindowBound (Data.historyGraph.tree.left.left.right.left.left.right) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_13 :
    indexedAll hasWindowBound (Data.historyGraph.tree.left.left.right.left.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedGraphVertices_11⟩, checkedGraphVertices_12⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_14 :
    indexedAll hasWindowBound (Data.historyGraph.tree.left.left.right.left.right) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_15 :
    indexedAll hasWindowBound (Data.historyGraph.tree.left.left.right.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedGraphVertices_13⟩, checkedGraphVertices_14⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_16 :
    indexedAll hasWindowBound (Data.historyGraph.tree.left.left.right.right.left.left) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_17 :
    indexedAll hasWindowBound (Data.historyGraph.tree.left.left.right.right.left.right) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_18 :
    indexedAll hasWindowBound (Data.historyGraph.tree.left.left.right.right.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedGraphVertices_16⟩, checkedGraphVertices_17⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_19 :
    indexedAll hasWindowBound (Data.historyGraph.tree.left.left.right.right.right) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_20 :
    indexedAll hasWindowBound (Data.historyGraph.tree.left.left.right.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedGraphVertices_18⟩, checkedGraphVertices_19⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_21 :
    indexedAll hasWindowBound (Data.historyGraph.tree.left.left.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedGraphVertices_15⟩, checkedGraphVertices_20⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_22 :
    indexedAll hasWindowBound (Data.historyGraph.tree.left.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedGraphVertices_10⟩, checkedGraphVertices_21⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_23 :
    indexedAll hasWindowBound (Data.historyGraph.tree.left.right.left.left.left.left) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_24 :
    indexedAll hasWindowBound (Data.historyGraph.tree.left.right.left.left.left.right) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_25 :
    indexedAll hasWindowBound (Data.historyGraph.tree.left.right.left.left.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedGraphVertices_23⟩, checkedGraphVertices_24⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_26 :
    indexedAll hasWindowBound (Data.historyGraph.tree.left.right.left.left.right) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_27 :
    indexedAll hasWindowBound (Data.historyGraph.tree.left.right.left.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedGraphVertices_25⟩, checkedGraphVertices_26⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_28 :
    indexedAll hasWindowBound (Data.historyGraph.tree.left.right.left.right.left.left) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_29 :
    indexedAll hasWindowBound (Data.historyGraph.tree.left.right.left.right.left.right) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_30 :
    indexedAll hasWindowBound (Data.historyGraph.tree.left.right.left.right.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedGraphVertices_28⟩, checkedGraphVertices_29⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_31 :
    indexedAll hasWindowBound (Data.historyGraph.tree.left.right.left.right.right) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_32 :
    indexedAll hasWindowBound (Data.historyGraph.tree.left.right.left.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedGraphVertices_30⟩, checkedGraphVertices_31⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_33 :
    indexedAll hasWindowBound (Data.historyGraph.tree.left.right.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedGraphVertices_27⟩, checkedGraphVertices_32⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_34 :
    indexedAll hasWindowBound (Data.historyGraph.tree.left.right.right.left.left.left) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_35 :
    indexedAll hasWindowBound (Data.historyGraph.tree.left.right.right.left.left.right) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_36 :
    indexedAll hasWindowBound (Data.historyGraph.tree.left.right.right.left.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedGraphVertices_34⟩, checkedGraphVertices_35⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_37 :
    indexedAll hasWindowBound (Data.historyGraph.tree.left.right.right.left.right) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_38 :
    indexedAll hasWindowBound (Data.historyGraph.tree.left.right.right.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedGraphVertices_36⟩, checkedGraphVertices_37⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_39 :
    indexedAll hasWindowBound (Data.historyGraph.tree.left.right.right.right.left) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_40 :
    indexedAll hasWindowBound (Data.historyGraph.tree.left.right.right.right.right) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_41 :
    indexedAll hasWindowBound (Data.historyGraph.tree.left.right.right.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedGraphVertices_39⟩, checkedGraphVertices_40⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_42 :
    indexedAll hasWindowBound (Data.historyGraph.tree.left.right.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedGraphVertices_38⟩, checkedGraphVertices_41⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_43 :
    indexedAll hasWindowBound (Data.historyGraph.tree.left.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedGraphVertices_33⟩, checkedGraphVertices_42⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_44 :
    indexedAll hasWindowBound (Data.historyGraph.tree.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedGraphVertices_22⟩, checkedGraphVertices_43⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_45 :
    indexedAll hasWindowBound (Data.historyGraph.tree.right.left.left.left.left.left) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_46 :
    indexedAll hasWindowBound (Data.historyGraph.tree.right.left.left.left.left.right) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_47 :
    indexedAll hasWindowBound (Data.historyGraph.tree.right.left.left.left.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedGraphVertices_45⟩, checkedGraphVertices_46⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_48 :
    indexedAll hasWindowBound (Data.historyGraph.tree.right.left.left.left.right) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_49 :
    indexedAll hasWindowBound (Data.historyGraph.tree.right.left.left.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedGraphVertices_47⟩, checkedGraphVertices_48⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_50 :
    indexedAll hasWindowBound (Data.historyGraph.tree.right.left.left.right.left.left) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_51 :
    indexedAll hasWindowBound (Data.historyGraph.tree.right.left.left.right.left.right) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_52 :
    indexedAll hasWindowBound (Data.historyGraph.tree.right.left.left.right.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedGraphVertices_50⟩, checkedGraphVertices_51⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_53 :
    indexedAll hasWindowBound (Data.historyGraph.tree.right.left.left.right.right) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_54 :
    indexedAll hasWindowBound (Data.historyGraph.tree.right.left.left.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedGraphVertices_52⟩, checkedGraphVertices_53⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_55 :
    indexedAll hasWindowBound (Data.historyGraph.tree.right.left.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedGraphVertices_49⟩, checkedGraphVertices_54⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_56 :
    indexedAll hasWindowBound (Data.historyGraph.tree.right.left.right.left.left.left) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_57 :
    indexedAll hasWindowBound (Data.historyGraph.tree.right.left.right.left.left.right) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_58 :
    indexedAll hasWindowBound (Data.historyGraph.tree.right.left.right.left.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedGraphVertices_56⟩, checkedGraphVertices_57⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_59 :
    indexedAll hasWindowBound (Data.historyGraph.tree.right.left.right.left.right) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_60 :
    indexedAll hasWindowBound (Data.historyGraph.tree.right.left.right.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedGraphVertices_58⟩, checkedGraphVertices_59⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_61 :
    indexedAll hasWindowBound (Data.historyGraph.tree.right.left.right.right.left) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_62 :
    indexedAll hasWindowBound (Data.historyGraph.tree.right.left.right.right.right) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_63 :
    indexedAll hasWindowBound (Data.historyGraph.tree.right.left.right.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedGraphVertices_61⟩, checkedGraphVertices_62⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_64 :
    indexedAll hasWindowBound (Data.historyGraph.tree.right.left.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedGraphVertices_60⟩, checkedGraphVertices_63⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_65 :
    indexedAll hasWindowBound (Data.historyGraph.tree.right.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedGraphVertices_55⟩, checkedGraphVertices_64⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_66 :
    indexedAll hasWindowBound (Data.historyGraph.tree.right.right.left.left.left.left) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_67 :
    indexedAll hasWindowBound (Data.historyGraph.tree.right.right.left.left.left.right) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_68 :
    indexedAll hasWindowBound (Data.historyGraph.tree.right.right.left.left.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedGraphVertices_66⟩, checkedGraphVertices_67⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_69 :
    indexedAll hasWindowBound (Data.historyGraph.tree.right.right.left.left.right) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_70 :
    indexedAll hasWindowBound (Data.historyGraph.tree.right.right.left.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedGraphVertices_68⟩, checkedGraphVertices_69⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_71 :
    indexedAll hasWindowBound (Data.historyGraph.tree.right.right.left.right.left.left) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_72 :
    indexedAll hasWindowBound (Data.historyGraph.tree.right.right.left.right.left.right) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_73 :
    indexedAll hasWindowBound (Data.historyGraph.tree.right.right.left.right.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedGraphVertices_71⟩, checkedGraphVertices_72⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_74 :
    indexedAll hasWindowBound (Data.historyGraph.tree.right.right.left.right.right) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_75 :
    indexedAll hasWindowBound (Data.historyGraph.tree.right.right.left.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedGraphVertices_73⟩, checkedGraphVertices_74⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_76 :
    indexedAll hasWindowBound (Data.historyGraph.tree.right.right.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedGraphVertices_70⟩, checkedGraphVertices_75⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_77 :
    indexedAll hasWindowBound (Data.historyGraph.tree.right.right.right.left.left.left) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_78 :
    indexedAll hasWindowBound (Data.historyGraph.tree.right.right.right.left.left.right) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_79 :
    indexedAll hasWindowBound (Data.historyGraph.tree.right.right.right.left.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedGraphVertices_77⟩, checkedGraphVertices_78⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_80 :
    indexedAll hasWindowBound (Data.historyGraph.tree.right.right.right.left.right) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_81 :
    indexedAll hasWindowBound (Data.historyGraph.tree.right.right.right.left) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedGraphVertices_79⟩, checkedGraphVertices_80⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_82 :
    indexedAll hasWindowBound (Data.historyGraph.tree.right.right.right.right.left) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_83 :
    indexedAll hasWindowBound (Data.historyGraph.tree.right.right.right.right.right) = true := by
  decide +kernel

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_84 :
    indexedAll hasWindowBound (Data.historyGraph.tree.right.right.right.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedGraphVertices_82⟩, checkedGraphVertices_83⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_85 :
    indexedAll hasWindowBound (Data.historyGraph.tree.right.right.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedGraphVertices_81⟩, checkedGraphVertices_84⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_86 :
    indexedAll hasWindowBound (Data.historyGraph.tree.right.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedGraphVertices_76⟩, checkedGraphVertices_85⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_87 :
    indexedAll hasWindowBound (Data.historyGraph.tree.right) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedGraphVertices_65⟩, checkedGraphVertices_86⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
private theorem checkedGraphVertices_88 :
    indexedAll hasWindowBound (Data.historyGraph.tree) = true := by
  exact Bool.and_eq_true_iff.mpr ⟨Bool.and_eq_true_iff.mpr
    ⟨by decide +kernel, checkedGraphVertices_44⟩, checkedGraphVertices_87⟩

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
/-- Proposition 24: every entry of the window-bound tree passes
`checkWindowVertex`. Each bounded check is verified by Lean's kernel. -/
theorem windowVertices_checked :
    indexedAll checkWindowVertex Data.windowBounds = true :=
  checkedWindowVertices_88

set_option maxHeartbeats 20000000 in
-- This finite certificate is reduced by the Lean kernel.
/-- Section 6.6: every vertex of the history graph has window bounds.
Each bounded check is verified by Lean's kernel. -/
theorem graphVertices_checked :
    indexedAll hasWindowBound Data.historyGraph.tree = true :=
  checkedGraphVertices_88

end Queens.Finite
