/* Table-driven generator of the greedy-queen rows (Section 7 of the paper).
 *
 * The local calculation of Section 7.2 has been compiled offline, by
 * tools/build_tables.py, into the table of generated/tables.h (Section 7.3):
 * a table position (one of 82 classes) and one input byte, holding four
 * earlier symbols of the queen word, select an entry giving
 *   - the successor table position,
 *   - the three to twelve new symbols of the queen word, and
 *   - the coordinate data of their queens, as in the coordinate formula of Section 7.3.
 *
 * The earlier symbols are regenerated by a chain of copies of the same
 * calculation (Section 7.1). Each inner copy produces the queen
 * word from sigma_30 onward, packed four symbols per byte, into a buffer of
 * ready bytes; it refills that buffer by reading bytes from the next copy
 * (the refill rule of Section 7.4). The outer copy, the QFGenerator, reads bytes from the first
 * inner copy and decodes the queen rows. The first thirty rows are a fixed
 * seed.
 *
 * Symbols are packed in order of increasing bit position: the first symbol
 * of a byte is in its two low bits.
 */
#include "queens_fast.h"
#include <assert.h>
#include <errno.h>
#include <limits.h>
#include <stdlib.h>

#include "../generated/tables.h"

/* The initial buffer budget, in bytes, of the first inner copy. Each further
 * copy has half the budget of the previous one, and at least one byte. */
#ifndef QF_BUFFER
#define QF_BUFFER 1024
#endif

_Static_assert(CHAR_BIT == 8, "This implementation requires 8-bit bytes");
_Static_assert(QF_BUFFER >= 1 && QF_BUFFER <= 1048576, "Invalid QF_BUFFER");
/* The table layout read below: one byte of four input symbols is added
 * directly to the base offset of the table position, and each entry holds
 * the offset of its own coordinate data. */
_Static_assert(QF_BLOCK == 4 && !QF_COMPACT && !QF_SEPARATE_PACKET,
               "Unexpected table layout");

/* Three padding bytes per buffer (Section 7.4). They hold the four initial
 * bytes of a new copy even when its budget is one, and they absorb the last
 * lookup of a refill: it starts below the budget, may end up to two bytes
 * past it, and stores four bytes at a time. */
#define PADDING 3u

/* An inner copy of the calculation (Section 7.1). */
typedef struct Copy Copy;
struct Copy {
    Copy *input;           /* The copy supplying our input bytes; NULL until needed. */
    uint32_t table_position;  /* Base offset in qf_table of the current class. */
    uint32_t next_ready;   /* Index of the next ready byte to hand out. */
    uint32_t ready_end;    /* Number of ready bytes in the buffer. */
    uint32_t budget;       /* A refill stops once it has this many bytes. */
    uint32_t carry;        /* Up to three computed symbols not yet forming a byte, */
    uint8_t carry_bits;    /* occupying this many low bits of carry (0, 2, 4, 6). */
#ifdef QF_INSTRUMENT
    uint64_t macro_steps, refill_calls;
#endif
    uint8_t ready[];       /* budget + PADDING bytes of packed symbols. */
};

/* The outer copy: it decodes rows instead of buffering symbols. */
struct QFGenerator {
    Copy *input;
    const uint8_t *block;  /* Coordinate data of the current block, from qf_packets:
                              [length, advance of m, advance of U, code_0, ...]. */
    uint64_t column;       /* The next column n to be returned. */
    uint64_t m;            /* Row reference m_0 at the start of the current block. */
    uint64_t upper_count;  /* U_0 = U(n_0 - 1) at the start of the current block. */
    uint32_t table_position;
    uint8_t block_position;   /* Rows of the current block already returned. */
    uint8_t failed;           /* Set after an allocation failure. */
#ifdef QF_INSTRUMENT
    uint64_t macro_steps;
#endif
};

/* Store the low four bytes of bits at where[0..3], least significant first.
 * Explicit shifts make this independent of the host byte order. The last
 * one to three bytes may be overwritten by the next store, and they always
 * lie within the padding. */
static inline void store_bytes(uint8_t *where, uint32_t bits)
{
    where[0] = (uint8_t)bits;
    where[1] = (uint8_t)(bits >> 8);
    where[2] = (uint8_t)(bits >> 16);
    where[3] = (uint8_t)(bits >> 24);
}

/* A new copy at the seed: its ready buffer holds the eighteen symbols
 * sigma_30 ... sigma_47 that the calculation produces before requesting any
 * input (Section 7.1). These are four complete bytes and two carried
 * symbols. */
static Copy *copy_create(unsigned budget)
{
    size_t bytes = sizeof(Copy) + (size_t)(budget + PADDING);
    Copy *c = (Copy *)calloc(1, bytes);
    if (!c) return NULL;
    c->table_position = QF_INITIAL_STATE;
    c->budget = budget;
    c->ready_end = QF_INITIAL_LENGTH / 4u;
    c->carry_bits = (uint8_t)(2u * (QF_INITIAL_LENGTH % 4u));
    c->carry = (uint32_t)(QF_INITIAL_SYMBOLS >> (c->ready_end * 8u));
    /* The eighteen symbols occupy 36 bits; the complete bytes fit in 32. */
    store_bytes(c->ready, (uint32_t)QF_INITIAL_SYMBOLS);
    assert(c->ready_end <= budget + PADDING);
    return c;
}

/* The table index for the current table position and one input byte.
 * Assertion builds check that the entry exists and belongs to this class;
 * in the actual process it always does (Section 7.4). */
static inline unsigned table_index(unsigned table_position, uint8_t input)
{
    unsigned index = table_position + input;
    assert(index < QF_SLOT_COUNT);
    assert(qf_owners[index] == table_position);
    assert(((qf_table[index] >> QF_LENGTH_SHIFT) & QF_LENGTH_MASK) != 0);
    return index;
}

/* Fields of a table entry. */
static inline unsigned entry_successor(uint64_t entry)
{
    return (unsigned)(entry & QF_STATE_MASK);
}
static inline unsigned entry_length(uint64_t entry)
{
    return (unsigned)((entry >> QF_LENGTH_SHIFT) & QF_LENGTH_MASK);
}
static inline uint32_t entry_symbols(uint64_t entry)
{
    return (uint32_t)((entry >> QF_SYMBOL_SHIFT) & QF_SYMBOL_MASK);
}

/* Refill the exhausted ready buffer of c (the refill rule of Section 7.4). Read input bytes
 * from the next copy, creating it on first use, and apply one table lookup
 * per byte, until at least budget complete bytes are ready. */
static int refill(Copy *c)
{
    unsigned end = 0, position = c->table_position, bits = c->carry_bits;
    uint32_t carry = c->carry;
    if (!c->input) {
        unsigned budget = c->budget > 1u ? c->budget / 2u : 1u;
        c->input = copy_create(budget);
        if (!c->input) return -1;
    }
    Copy *input = c->input;
    do {
        if (input->next_ready == input->ready_end && refill(input)) return -1;
        uint8_t byte = input->ready[input->next_ready++];
        uint64_t entry = qf_table[table_index(position, byte)];
        /* Append the new symbols after the carried ones, store every
         * complete byte, and carry the remaining zero to three symbols. */
        uint32_t pending = carry | (entry_symbols(entry) << bits);
        unsigned total = bits + 2u * entry_length(entry);
        store_bytes(c->ready + end, pending);
        end += total / 8u;
        carry = pending >> (total & ~7u);
        bits = total & 7u;
        position = entry_successor(entry);
#ifdef QF_INSTRUMENT
        ++c->macro_steps;
#endif
    } while (end < c->budget);
    assert(end <= c->budget + 2u);
    c->table_position = position;
    c->carry = carry;
    c->carry_bits = (uint8_t)bits;
    c->next_ready = 0;
    c->ready_end = end;
#ifdef QF_INSTRUMENT
    ++c->refill_calls;
#endif
    return 0;
}

QFGenerator *qf_create(void)
{
    QFGenerator *g = (QFGenerator *)calloc(1, sizeof(*g));
    if (!g) return NULL;
    /* The first block is the eighteen seed outputs for columns 30..47. */
    g->block = qf_packets + QF_INITIAL_PACKET;
    g->m = QF_INITIAL_M;
    g->upper_count = QF_INITIAL_UPPER;
    g->table_position = QF_INITIAL_STATE;
    return g;
}

void qf_destroy(QFGenerator *g)
{
    if (!g) return;
    Copy *c = g->input;
    while (c) {
        Copy *next = c->input;
        free(c);
        c = next;
    }
    free(g);
}

uint64_t qf_position(const QFGenerator *g) { return g ? g->column : 0; }

/* Finish the current block, whose rows have all been returned, and start
 * the next one: advance the counters m and U by the block's totals, then
 * look up the next input byte. This happens only when another row is
 * requested, so a caller stopping at a block boundary causes no lookup. */
static inline int next_block(QFGenerator *g)
{
    g->m += g->block[1];
    g->upper_count += g->block[2];
    if (!g->input) {
        g->input = copy_create(QF_BUFFER);
        if (!g->input) return -1;
    }
    Copy *input = g->input;
    if (input->next_ready == input->ready_end && refill(input)) return -1;
    unsigned index = table_index(g->table_position, input->ready[input->next_ready++]);
    uint64_t entry = qf_table[index];
    g->table_position = entry_successor(entry);
    g->block = qf_packets + (entry >> QF_PACKET_SHIFT);
    g->block_position = 0;
#ifdef QF_INSTRUMENT
    ++g->macro_steps;
#endif
    return 0;
}

static int validate(QFGenerator *g, uint64_t count)
{
    if (!g || g->failed) { errno = EINVAL; return -1; }
    if (count > UINT64_MAX / 2u - g->column) { errno = ERANGE; return -1; }
    return 0;
}

/* Decode one coordinate code of the coordinate formula of Section 7.3. The high bit selects the
 * base: bases[0] = m_0 for a lower queen, bases[1] = n_0 + U_0 for an upper
 * queen. The low seven bits are the offset from that base. */
static inline uint64_t decode(unsigned code, const uint64_t bases[2])
{
    return bases[code >> 7] + (code & 127u);
}

int qf_fill(QFGenerator *g, uint64_t *rows, size_t count)
{
    if ((!rows && count) || validate(g, (uint64_t)count)) {
        if (!rows && count) errno = EINVAL;
        return -1;
    }
    size_t done = 0;
    while (done < count && g->column < 30u)
        rows[done++] = qf_seed_queens[g->column++];
    while (done < count) {
        if (g->block_position == g->block[0] && next_block(g)) {
            g->failed = 1;
            return -1;
        }
        unsigned start = g->block_position;
        unsigned take = g->block[0] - start;
        if (take > count - done) take = (unsigned)(count - done);
        const uint8_t *codes = g->block + 3u + start;
        /* n_0 = column - start is the first column of the block. */
        uint64_t bases[2] = {g->m, g->column - start + g->upper_count};
        for (unsigned i = 0; i < take; ++i) rows[done + i] = decode(codes[i], bases);
        done += take;
        g->column += take;
        g->block_position = (uint8_t)(start + take);
    }
    return 0;
}

int qf_next(QFGenerator *g, uint64_t *row) { return qf_fill(g, row, 1); }

/* The same loop as qf_fill, folding each row into the checksum instead of
 * storing it. */
int qf_hash(QFGenerator *g, uint64_t count, uint64_t *hash, uint64_t *last)
{
    if (!hash || !last || validate(g, count)) {
        if (!hash || !last) errno = EINVAL;
        return -1;
    }
    uint64_t h = *hash, y = *last;
    while (count && g->column < 30u) {
        y = qf_seed_queens[g->column++];
        h = (h ^ y) * UINT64_C(1099511628211);
        --count;
    }
    while (count) {
        if (g->block_position == g->block[0] && next_block(g)) {
            g->failed = 1;
            return -1;
        }
        unsigned start = g->block_position;
        unsigned take = g->block[0] - start;
        if (take > count) take = (unsigned)count;
        const uint8_t *codes = g->block + 3u + start;
        uint64_t bases[2] = {g->m, g->column - start + g->upper_count};
        for (unsigned i = 0; i < take; ++i) {
            y = decode(codes[i], bases);
            h = (h ^ y) * UINT64_C(1099511628211);
        }
        count -= take;
        g->column += take;
        g->block_position = (uint8_t)(start + take);
    }
    *hash = h;
    *last = y;
    return 0;
}

QFStats qf_stats(const QFGenerator *g)
{
    QFStats s = {0};
    if (!g) return s;
    s.levels = 1;
    s.generator_bytes = sizeof(*g);
    s.producer_record_bytes = sizeof(Copy);
    s.heap_bytes = sizeof(*g);
    s.static_data_bytes = sizeof(qf_table) + sizeof(qf_packets) + sizeof(qf_seed_queens);
#ifndef NDEBUG
    s.static_data_bytes += sizeof(qf_owners);
#endif
#ifdef QF_INSTRUMENT
    s.outer_macro_steps = g->macro_steps;
#endif
    for (const Copy *c = g->input; c; c = c->input) {
        size_t buffer_bytes = (size_t)(c->budget + PADDING);
        ++s.levels;
        s.symbol_buffer_bytes += buffer_bytes;
        s.heap_bytes += sizeof(*c) + buffer_bytes;
#ifdef QF_INSTRUMENT
        s.inner_macro_steps += c->macro_steps;
        s.refill_calls += c->refill_calls;
#endif
    }
    return s;
}
